### ISSUE TITLE
Graph query limit when asking for uniswap trades

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#2709] opened 2021-04-10 11:45 UTC
TheGraph seems to have a limit in how much you can skip

```
Failed to retrieve Uniswap trades: The Graph query to query ($limit: Int!, $offset: Int!, $address: Bytes!, $start_ts: BigInt!, $end_ts: BigInt!){swaps_from: swaps ( first: $limit, skip: $offset, where: { from: $address, timestamp_gte: $start_ts, timestamp_lte: $end_ts, } ) { transaction { swaps { id logIndex sender to timestamp pair { token0 { id decimals name symbol } token1 { id decimals name symbol } } amount0In amount0Out amount1In amount1Out } } } swaps_to: swaps ( first: $limit, skip: $offset, where: { to: $address, timestamp_gte: $start_ts, timestamp_lte: $end_ts, } ) { transaction { swaps { id logIndex sender to timestamp pair { token0 { id decimals name symbol } token1 { id decimals name symbol } } amount0In amount0Out amount1In amount1Out } } }} failed due to {'message': 'The `skip` argument must be between 0 and 5000, but is 6000'}. No retries left.
```

**Comment by LefterisJP** [comment] 2021-04-10 15:33
Hey @yabirgb I think this is a duplicate of https://github.com/rotki/rotki/issues/2450. Would you like to handle it at some point?

I am going to close this as a duplicate.

**Closed by LefterisJP** 2021-04-10 15:33 UTC
Labels: backend
