### ISSUE TITLE
Anonymized Premium Accounts

### ISSUE THREAD

**Issue by ty-han** [rotki/rotki#2688] opened 2021-04-07 19:43 UTC
## Abstract
Remove all personally identifiable information requirements from Premium Subscription signup process.

## Motivation

Most privacy-centric individuals, who are prime customers for Rotki's Premium Subscription, will be very leery to attach their name and address to their crypto related accounts.  Even if all efforts are made to encrypt and privatize crypto balances in the app, there is a psychological aversion for people such as myself to provide such information.  By removing this requirement you will gain more paid customers.  Especially for users who are paying by crypto, I am not sure why a name and address are required.  Even email should be removed from the account if possible. I have to imagine that there are ways to secure accounts now without an email address.

**Comment by LefterisJP** [comment] 2021-04-07 20:09
Hey @ty-han thank you for your interest in rotki!

Closing as duplicate of https://github.com/rotki/rotki/issues/1343

As it's already mentioned there we may at some point manage to create something like this but needs a lot of work with regulators and accountants to make sure we are compliant.

>  Especially for users who are paying by crypto, I am not sure why a name and address are required.

It's actually pretty simple. Just like in most countries, so is it also in Germany where we are a registered business, that you require to provide a name and address for each electronic payment you receive. Crypto is money too and makes no difference.

Keep in mind we have asolutely no way to verify that data is correct. We just need to get whatever the user gives us and keep it around to show it when asked.

We have already gone to great lengths to periodically move these user data offline from the website so as not to keep it online for too long.

> Even email should be removed from the account if possible. I have to imagine that there are ways to secure accounts now without an email address.

Email is a way of communication regarding your subscription. Most users use one-off and private centric emails when registering.

----

This topic comes up from time to time in our discord community. Please do join if you are interested: https://discord.gg/aGCxHG7

**Closed by LefterisJP** 2021-04-07 20:09 UTC
