### ISSUE TITLE
Add price information in the assets overview

### ISSUE THREAD

**Issue by efnats** [rotki/rotki#2026] opened 2021-01-05 17:46 UTC
## Abstract

The Assets overview in the dashboard doesn't show information about per coin price and price development

## Motivation

Managing a crypto portfolio is connected to managing price developments and base decisions about buying or selling on that. It would add value to not only show the current price but also the percentage gains/losses in the last 24h/7d/30d

**Comment by LefterisJP** [comment] 2021-01-05 18:18
Hey @efnats I completely agree. I think we already got an issue for this and it's https://github.com/rotki/rotki/issues/701. Can I close this one as a duplicate?

**Closed by LefterisJP** 2021-01-05 18:18 UTC

**Comment by efnats** [comment] 2021-01-07 13:13
Hey @LefterisJP, thanks for your quick response.

I believe its not a duplicate. #701 refers to percentage profit/loss. While this would probably also include net prices additionally being displayed, my suggestion is a simpler one.
For the time beeing include an additional column and display current prices in the user-selected currency. This information is being polled by the programm anyways. Its a UI improvement/change suggestion - not really a new feature request.

**Comment by LefterisJP** [comment] 2021-01-07 15:13
Aha thanks for the clarification @efnats. 

Then it is a duplicate of another issue: https://github.com/rotki/rotki/issues/1228

We will do that at some point, it's a valid request.
