### ISSUE TITLE
Add the ability to "save reports"

### ISSUE THREAD

**Issue by chevdor** [rotki/rotki#1951] opened 2020-12-19 19:37 UTC
## Abstract

Allow "saving reports" to save time and processing. This is actually describing a simple caching mechanism.

## Motivation

Generating a report can take a while. 
The input is a small number of parameters and the output can be a huge amount of data.
The output is made of what is called the "overview" in Rokti (=aggregated values) as well as all the data used for the calculation.

## Specification

I would propose to list the parameters involved in the generation of a report:
- list of exchange accounts / keys
- date from/to
- settings

The goal is to include all the parameters that would result in a different output.

Those parameters can be packed and compressed into a hash used as key in a disctionnary that allows storing the overview (=aggregated results) or even the entire dataset.

If a user requests a report with parameters that have already been processed in the past, we can simply load the cached results.

In case the results could change (new algorithm, bug fix), a button to "ignore the cache" or "clear the cache" could be offered to the user.

**Comment by LefterisJP** [comment] 2020-12-19 20:30
This is most probably a duplicate of: https://github.com/rotki/rotki/issues/1214

I think that ideally we would want to tackle the underlying issues of the report taking a long time. All the things that take time should be cached themselves and then if all is cached, then generating a tax report a second time should be quite fast.

Related issue: https://github.com/rotki/rotki/issues/968

If you don't think this is a duplicate then please re-open.

**Closed by LefterisJP** 2020-12-19 20:30 UTC

**Comment by chevdor** [comment] 2020-12-20 09:41
ok, keep in mind that caching single queries will improve but not has much than also caching the end result.
