### ISSUE TITLE
loss of connectivity should not spam 100s of Gemini errors or lose Premium features

### ISSUE THREAD

**Issue by aspiers** [rotki/rotki#8940] opened 2024-11-23 12:17 UTC
## Problem Definition

When my laptop loses connectivity, this can trigger an avalanche of errors which aren't really errors, just intermittent failures.  In particular, deactivating Premium features due to loss of connectivity seems way too sensitive:

![image](https://github.com/user-attachments/assets/8c9f09ec-e8be-466e-8a86-2bf853bc2a32)

The FDUSD notification is unrelated, but the vast majority come from Gemini, so perhaps it's just an issue with that adapter and the Premium detection code?

## Logs

Available on request, but I assume this is very easy to reproduce.

### System Description

Operating system: openSUSE
Rotki version: rotki-linux_x86_64-v1.36.0.AppImage

**Comment by aspiers** [comment] 2024-11-23 15:49
Seems it's not just these two categories.  After suspending and resuming my laptop, I got another 100 notifications, this time with a bunch from trying to connect to rotki.com:

![image](https://github.com/user-attachments/assets/45c95f85-f48d-439a-abef-f03bdff6e4a3)

**Comment by LefterisJP** [comment] 2024-11-23 16:07
This is a known issue. rotki is an app that needs network connection for many things. The app constantly queries data from various servers periodically in the background. It's not made to work completely offline.

The premium features in particular are a really important part of this as we had a very serious case (which also involved legal action from our part due to being a closed source fork) of lack of liveness check to cheat premium even on a fork of rotki.

Naturally some things can be improved a lot, like this spamming you see. The app needs an "offline mode". But the implementation needs some thinking and it's neither straightforward nor trivial.

That's why the issue already exists and is quite old: https://github.com/rotki/rotki/issues/859 as it's not a priority.

Closing this as duplicate of that.

**Closed by LefterisJP** 2024-11-23 16:07 UTC
