### ISSUE TITLE
"The Python backend crashed."  macOS Mojave

### ISSUE THREAD

**Issue by Michael-A-Heuer** [rotki/rotki#767] opened 2020-03-06 23:03 UTC
Got the same error as in issue #693 for rotki 1.2.0 on my mac. I only shortly see the guy and then it shows an error saying that "The Python backend crashed."

```
uname -a
Darwin heuerMBP-host 18.7.0 Darwin Kernel Version 18.7.0: Thu Jan 23 06:52:12 PST 2020; root:xnu-4903.278.25~1/RELEASE_X86_64 x86_64
```

`rotkehlchen.log`
```
07/03/2020 00:00:02 CET -- DEBUG:rotkehlchen.rotkehlchen:Main loop start
07/03/2020 00:00:02 CET -- DEBUG:rotkehlchen.rotkehlchen:Main loop end
07/03/2020 00:00:05 CET -- DEBUG:rotkehlchen.api.rest:Request successful response={"result": {"our_version": "1.2.0", "latest_version": "v1.2.0", "download_url": null}, "message": ""}, status_code=200
07/03/2020 00:00:05 CET -- INFO:rotkehlchen.api.server.pywsgi:127.0.0.1 - - [2020-03-07 00:00:05] "GET /api/1/version HTTP/1.1" 200 290 0.811157
07/03/2020 00:00:17 CET -- DEBUG:rotkehlchen.rotkehlchen:Main loop start
07/03/2020 00:00:17 CET -- DEBUG:rotkehlchen.rotkehlchen:Main loop end```
````

`rotki_electron.log`
```
Rotki Electron Log initialization
2020-03-06T22:52:13.982Z: Starting packaged python subprocess: /Applications/rotki.app/Contents/Resources/rotkehlchen_py_dist/rotkehlchen-1.2.0-macos --api-port 4242 --api-cors app://* --logfile /Users/michaelheuer/Library/Logs/rotki/rotkehlchen.log
2020-03-06T22:52:13.992Z: The Python sub-process started on port: 4242 (PID: 79082)
2020-03-06T22:52:16.560Z: The Python sub-process exited with signal: null (Code: 255)
```

**Comment by LefterisJP** [comment] 2020-03-07 00:25
@Michael-A-Heuer Hello! Thanks for trying Rotki out. Have you used it before? And have previous versions worked in your system?

It works fine in my OSX machine but I am not able to upgrade to Mojave, so can't say we have the exact same system setup.

At first glance the logs do not provide any useful information so I can't say much without reproducing the problem myself.

**Comment by Michael-A-Heuer** [comment] 2020-03-07 00:29
Hey, yes it worked the first time I started the app after I downloaded it. I could log into my account and add some addresses. Then the second time I started the app, the error came up. The same happened for me with the previous version (not sure if it was 1.1.0 or 1.0.0).

**Comment by LefterisJP** [comment] 2020-03-07 08:27
Does it work after a restart of the system?

**Comment by Michael-A-Heuer** [comment] 2020-03-07 08:57
Yes, it does but when I close and open the app again, I get the same error.

**Comment by kelsos** [comment] 2020-03-07 10:52
It looks quite similar to the issue we had in windows where the python process doesn't terminate when exiting the app, and since the previous process is holding the 4242 port the new cannot start.

**Comment by LefterisJP** [comment] 2020-03-07 16:37
@Michael-A-Heuer thanks that's really helpful already. I will try to reproduce it from Monday when I am back in Berlin and have access to my old mac.

For now as a workaround try to see if there is a lingering process in OSX from rotki and kill it. Is there something like a task manager in OSX? If yes then you can do it from there. If not from the terminal I also suppose it works:

```
ps aux | grep rotki
kill -9 PIDOFPROCESS
```

Where `PIDOFPROCESS` is the PID shown in any lingering process.

Also a question. How do you close the app? Did you right click in the docker and say "Exit/Close"? If not I believe electron does not close the app but lets it run in the background by default. Which does not really work for rotki so I think we will have to change this behaviour.

@kelsos Could be. But could alos be related to the way OSX terminates the app (it does not) if you press the [X] to close the window. It just closes the window but does not kill anything.

**Comment by Michael-A-Heuer** [comment] 2020-03-07 23:27
Yes, I closed it in the dock. Usually, I would just press cmd+q but this does not work with rotki.

**Comment by LefterisJP** [comment] 2020-03-07 23:30
All right so I will try to see how that can happen with python process not terminating while the electron one does. @kelsos also if you got any ideas write them here.

@Michael-A-Heuer I suppose you have a workaround as I described [above](https://github.com/rotki/rotki/issues/767#issuecomment-596106225) until we manage to reproduce and fix?

**Comment by Michael-A-Heuer** [comment] 2020-03-07 23:32
Yes, thank you for your help and for your awesome app! =)

**Comment by kelsos** [comment] 2020-03-09 08:31
@LefterisJP I would suggest to fix it properly on OSX. Add a mechanism to detect if it was not closed but it was still in the background. Basically introduce some check for an already running python process in the background.

**Comment by LefterisJP** [comment] 2020-03-09 09:07
>  would suggest to fix it properly on OSX. Add a mechanism to detect if it was not closed but it was still in the background. Basically introduce some check for an already running python process in the background.

Hmmm but I am not sure if that's a proper fix. That is a fix, but not a proper one. The proper fix would be to figure out why it would ever still keep running in the background and then prevent that from happening.

**Comment by kelsos** [comment] 2020-03-09 09:09
@LefterisJP I am under the impression that not terminating the app and keeping it the background is how OSX handles apps.

**Comment by Michael-A-Heuer** [comment] 2020-03-09 19:08
No, you can terminate an app in macOS. You just 
![image](https://user-images.githubusercontent.com/20623991/76248503-bce8ef80-6241-11ea-95f5-35b0006ec008.png)

**Comment by kelsos** [comment] 2020-03-09 19:30
@Michael-A-Heuer Yes but if you don't terminate the app explicitly what is the default behavior of the system? (Sorry not an OSX user). My impression is that by default the applications are not terminated but they are kept in the background instead so that you can resume from where you left.

**Comment by LefterisJP** [comment] 2020-03-09 20:14
So @Michael-A-Heuer I need some help here. I tried the following in my OSX machine (it's High Sierra and I can't upgrade further):

1. Downloaded Rotki v1.2.0 for OSX.
2. Ran it and logged in and looked around
3. Right clicked in the dock and pressed Quit
4. Opened it again, logged in and looked around.

I could not reproduce the issue you are seeing. From what I understand this is enough for you to reproduce. Is that correct?

Looking at the logs you gave a bit more carefully the dates don't match. Can you try this again and check if a new file appears for both `rotkehlchen.log` and `rotki_electron.log` when you follow the steps I tried? We have to see if the backend starts or if it does not start at all. If it does not start all no new rotkehlchen.log will be made.

Does it always happen the second time you open it? When it happens can you show me the output of `ps aux | grep rotki`? In general if it always happens please try to see what `ps aux | grep rotki` gives you after closing the app.

Also really important to know if that is totally new for you and if versions before 1.2.0 worked fine for you. Or if this is the first time you are trying out Rotki.

**Comment by Michael-A-Heuer** [comment] 2020-03-10 22:19
@LefterisJP The first version I downloaded was 1.0.0 or 1.10 (can't remember). After playing around with it, I closed the app and couldn't sign in back in without the aforementioned error. 
A few days later, I saw that 1.2.0 is available and downloaded it. 
After the fresh installation, I could sign in. After closing the app, the same error occurred again.
Then, I posted this issue and you told me to restart my MacBook (I often leave it running for many days while using it and rarely restart it). After the restart, it worked. Closing the app again resulted in the same problem.
Today, I opened and closed the app and it works. I cannot reproduce the error. A new file is generated for both `.log` files if I close and reopen the app.

**Comment by kelsos** [comment] 2020-03-19 19:41
I managed to confirm the issue on OSX Catalina on the last release. 
When quitting the python process would keep running in the background causing this issue.

After #795 was merged I did try packaging the app again and run the same test. Now closing the app and starting it again seems to work without any issue.

**Comment by LefterisJP** [comment] 2020-03-19 19:43
That's great! So once v1.3.0 is released (very soon) this can also be considered solved.

**Comment by kelsos** [comment] 2020-03-19 19:46
We still have to get a confirmation of it being fixed on Mojave but as soon as that is confirmed I would say yes.

**Comment by Michael-A-Heuer** [comment] 2020-03-19 20:37
I will also give you a feedback when 1.3.0 is out. Currently, I cannot reproduce the error in 1.2.0. I am Glad that @kelsos could reproduce this issue and that this is not caused by some messed up python distribution on my computer.

**Comment by LefterisJP** [comment] 2020-03-20 18:22
@Michael-A-Heuer Rotki v1.3.0 is out: https://github.com/rotki/rotki/releases/tag/v1.3.0

**Comment by Michael-A-Heuer** [comment] 2020-03-24 15:01
Works fine for me.

**Comment by kelsos** [comment] 2020-03-24 15:03
@Michael-A-Heuer thanks for confirming :)

**Closed by kelsos** 2020-03-24 15:03 UTC
