### ISSUE TITLE
eursCRV asset not recognized

### ISSUE THREAD

**Issue by bloxster** [rotki/rotki#2458] opened 2021-02-27 08:52 UTC
## Problem Definition

Curve.fi pool EURS/SEUR not recognized

## Logs

Backend messages
Unsupported asset eursCRV with address 0x194eBd173F6cDacE046C53eACcE9B953F28411d1 encountered during DeFi protocol queries
February 27, 2021 9:38 AM

### System Description

Operating system: MacOS Big Sur 11.0.1
Rotki version: 14.2

[rotkehlchen.log.zip](https://github.com/rotki/rotki/files/6054011/rotkehlchen.log.zip)

**Comment by LefterisJP** [comment] 2021-02-27 09:06
Hey @bloxster thanks this is part of all the new curve pools that we don't yet support. We will address this soon. The issue is already here: https://github.com/rotki/rotki/issues/2456

So I am closing this as a duplicate. Follow that other issue to track implementation.

**Closed by LefterisJP** 2021-02-27 09:06 UTC
