### ISSUE TITLE
Track all new curve LP tokens

### ISSUE THREAD

**Issue by auryn-macmillan** [rotki/rotki#2456] opened 2021-02-26 19:39 UTC
## Abstract

Many curve LP tokens are not accounted for in Rotki, currently. 

## Specification

There is a [Curve Registry contract](https://etherscan.io/address/0x7D86446dDb609eD0F5f8684AcF30380a356b2B4c#readContract) that keeps track of all of Curve's pools.
`pool_count` returns the number of pools.
`pool_list` returns the pool address for a given index.
`get_lp_token` returns the LP token address for a given pool address.
With this, Rotki should be able to automatically track all Curve pool tokens.

For the time being, here is a list of all of the current pools and their tokens.

Index | Pool | LP Token
-- | -- | --
0 | 0xbEbc44782C7dB0a1A60Cb6fe97d0b483032FF1C7 | 0xbEbc44782C7dB0a1A60Cb6fe97d0b483032FF1C7
1 | 0x79a8C46DeA5aDa233ABaFFD40F3A0A2B1e5A4F27 | 0x3B3Ac5386837Dc563660FB6a0937DFAa5924333B
2 | 0xA2B47E3D5c44877cca798226B7B8118F9BFb7A56 | 0x845838DF265Dcd2c412A1Dc9e959c7d08537f8a2
3 | 0x4f062658EaAF2C1ccf8C8e36D6824CDf41167956 | 0xD2967f45c4f384DEEa880F807Be904762a3DeA07
4 | 0x4CA9b3063Ec5866A4B82E437059D2C43d1be596F | 0xb19059ebb43466C323583928285a49f558E572Fd
5 | 0x3eF6A01A0f81D6046290f3e2A8c5b843e738E604 | 0x5B5CFE992AdAC0C9D48E05854B2d91C73a003858
6 | 0xE7a24EF0C5e95Ffb0f6684b813A78F2a3AD7D171 | 0x6D65b498cb23deAba52db31c93Da9BFFb340FB8F
7 | 0x8474DdbE98F5aA3179B3B3F5942D724aFcdec9f6 | 0x1AEf73d49Dedc4b1778d0706583995958Dc862e6
8 | 0x06364f10B501e868329afBc005b3492902d6C763 | 0xD905e2eaeBe188fc92179b6350807D8bd91Db0D8
9 | 0x93054188d876f558f4a66B2EF1d97d16eDf0895B | 0x49849C98ae39Fff122806C06791Fa73784FB3675
10 | 0xC18cC39da8b11dA8c3541C598eE022258F9744da | 0xC2Ee6b0334C261ED60C72f6054450b61B8f18E35
11 | 0x7fC77b5c7614E1533320Ea6DDc2Eb61fa00A9714 | 0x075b1bb99792c9E1041bA13afEf80C91a1e70fB3
12 | 0xA5407eAE9Ba41422680e2e00537571bcC53efBfD | 0xC25a3A3b969415c80451098fa907EC722572917F
13 | 0xC25099792E9349C7DD09759744ea681C7de2cb66 | 0x64eda51d3Ad40D56b9dFc5554E06F94e1Dd786Fd
14 | 0x3E01dD8a5E1fb3481F0F589056b428Fc308AF0Fb | 0x97E2768e8E73511cA874545DC5Ff8067eB19B787
15 | 0x0f9cb53Ebe405d49A0bbdBD291A65Ff571bC83e1 | 0x4f3E8F405CF5aFC05D68142F3783bDfE13811522
16 | 0x52EA46506B9CC5Ef470C5bf89f17Dc28bB35D85C | 0x9fC689CCaDa600B6DF723D9E47D84d76664a1F23
17 | 0x45F783CCE6B7FF23B2ab2D70e416cdb7D6055f51 | 0xdF5e0e81Dff6FAF3A7e52BA697820c5e32D806A8
18 | 0x8038C01A0390a8c547446a0b2c18fc9aEFEcc10c | 0x3a664Ab939FD8482048609f652f9a0B0677337B9
19 | 0x071c661B4DeefB59E2a3DdB20Db036821eeE8F4b | 0x410e3E86ef427e30B9235497143881f717d93c2A
20 | 0xd81dA8D904b52208541Bade1bD6595D8a251F8dd | 0x2fE94ea3d5d4a175184081439753DE15AeF9d614
21 | 0x7F55DDe206dbAD629C080068923b36fe9D6bDBeF | 0x2fE94ea3d5d4a175184081439753DE15AeF9d614
22 | 0x890f4e345B1dAED0367A877a1612f86A1f86985f | 0x94e131324b6054c0D789b190b2dAC504e4361b53
23 | 0x0Ce6a5fF5217e38315f87032CF90686C96627CAA | 0x194eBd173F6cDacE046C53eACcE9B953F28411d1
24 | 0xc5424B857f758E906013F3555Dad202e4bdB4567 | 0xA3D87FffcE63B53E0d54fAa1cc983B7eB0b74A9c
25 | 0xDeBF20617708857ebe4F679508E7b7863a8A8EeE | 0xFd2a8fA60Abd58Efe3EeE34dd494cD491dC14900
26 | 0xDC24316b9AE028F1497c275EB9192a3Ea0f67022 | 0x06325440D014e39736583c165C2963BA99fAf14E
27 | 0xA96A65c051bF88B4095Ee1f2451C2A9d43F53Ae2 | 0xaA17A236F2bAdc98DDc0Cf999AbB47D47Fc0A6Cf
28 | 0xEB16Ae0052ed37f479f7fe63849198Df1765a733 | 0x02d341CcB60fAaf662bC0554d13778015d1b285C
29 | 0x2dded6Da1BF5DBdF597C45fcFaa3194e53EcfeAF | 0x5282a4eF67D9C33135340fB3289cc1711c13638C
30 | 0xF178C0b5Bb7e7aBF4e12A4838C7b7c5bA2C623c0 | 0xcee60cFa923170e4f8204AE08B4fA6A3F5656F3a
31 | 0x42d7025938bEc20B69cBae5A77421082407f053A | 0x7Eb40E450b9655f4B3cC4259BCC731c63ff55ae6

**Comment by LefterisJP** [comment] 2021-02-28 12:15
I would like to improve the way we do things and end up autodetecting those without too much manual work.

After a bit of thinking I think that this ties in close with the ability of having custom ethereum tokens entered by the user (or rotki itself): https://github.com/rotki/rotki/issues/2456

So I will implement that as a starting point.

**Comment by WyseNynja** [comment] 2021-03-15 20:51
> I would like to improve the way we do things and end up autodetecting those without too much manual work.
> 
> After a bit of thinking I think that this ties in close with the ability of having custom ethereum tokens entered by the user (or rotki itself): #2456
> 
> So I will implement that as a starting point.

I think you linked to the wrong issue. #2456 is this issue.

How long do you think that will take to do? In the mean time, would it be simple to add these new pool addresses to the existing list? Or is that more complicated than I'm thinking.

**Comment by LefterisJP** [comment] 2021-03-15 21:40
Oh yes. The issue is: https://github.com/rotki/rotki/issues/1519

Which is now done. But still we are in the process of doing a refactor around some things in the way we handle assets. This will be done after this. Can't really give an ETA but we generally have fast release schedules.

**Comment by LefterisJP** [comment] 2021-07-14 13:10
This should now be fixed by the various PRs that @yabirgb made.

**Closed by LefterisJP** 2021-07-14 13:10 UTC
Labels: ETH DeFi
