### ISSUE TITLE
CeFI Interest earning stablecoins

### ISSUE THREAD

**Issue by drgonzo31** [rotki/rotki#2571] opened 2021-03-16 00:30 UTC
## Abstract
Support for balances and interest earned from the following CeFI platforms:
Nexo, BlockFi, Ledn, Celsius.network

## Motivation
Rotki already supports interest earned on stablecoins for AAVE.  It would be great to include support for some of the CeFI platforms for tax reasons.

**Comment by LefterisJP** [comment] 2021-03-16 00:36
This issue is a duplicate of https://github.com/rotki/rotki/issues/2224, https://github.com/rotki/rotki/issues/1674, https://github.com/rotki/rotki/issues/1516.

Please search already existing issues before opening a new one. If we are missing an issue for a specific service open an issue per service.

**Closed by LefterisJP** 2021-03-16 00:36 UTC
