### ISSUE TITLE
UI exception at trying to show asset movement address/transaction link

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#2617] opened 2021-03-21 16:12 UTC
## Abstract

After creating v1.15.2 in master  and merging it back to develop there was few conflicts to fix which I did. But then when trying to look at the asset movements via the UI,when pressing expand to see address and transaction hash there is a UI exception.

![2021-03-21_17-06](https://user-images.githubusercontent.com/1658405/111912012-0466a600-8a68-11eb-82b7-6b38b9fdbada.png)

```
vue.runtime.esm.js:619 [Vue warn]: Error in render: "TypeError: Cannot read property 'address' of undefined"

found in

---> <HashLink> at src/components/helper/HashLink.vue
       <MovementLinks> at src/components/history/MovementLinks.vue
         <VCard>
           <VSimpleTable>
             <VData>
               <VDataTable>
                 <DataTable> at src/components/helper/DataTable.vue
                   <VSheet>
                     <VCard>
                       <DepositsWithdrawals> at src/views/history/DepositsWithdrawals.vue
                         <VTabItem>
                           <VTabsItems>
                             <VTabs>
                               <TabNavigation> at src/components/helper/TabNavigation.vue
                                 <History> at src/views/history/History.vue
                                   <VMain>
                                     <VApp>
                                       <App> at src/App.vue
                                         <Root>
warn @ vue.runtime.esm.js:619
logError @ vue.runtime.esm.js:1884
globalHandleError @ vue.runtime.esm.js:1879
handleError @ vue.runtime.esm.js:1839
Vue._render @ vue.runtime.esm.js:3550
updateComponent @ vue.runtime.esm.js:4066
get @ vue.runtime.esm.js:4479
Watcher @ vue.runtime.esm.js:4468
mountComponent @ vue.runtime.esm.js:4073
Vue.$mount @ vue.runtime.esm.js:8415
init @ vue.runtime.esm.js:3118
createComponent @ vue.runtime.esm.js:5978
createElm @ vue.runtime.esm.js:5925
createChildren @ vue.runtime.esm.js:6053
createElm @ vue.runtime.esm.js:5954
createChildren @ vue.runtime.esm.js:6053
createElm @ vue.runtime.esm.js:5954
patch @ vue.runtime.esm.js:6477
Vue._update @ vue.runtime.esm.js:3945
updateComponent @ vue.runtime.esm.js:4066
get @ vue.runtime.esm.js:4479
Watcher @ vue.runtime.esm.js:4468
mountComponent @ vue.runtime.esm.js:4073
Vue.$mount @ vue.runtime.esm.js:8415
init @ vue.runtime.esm.js:3118
createComponent @ vue.runtime.esm.js:5978
createElm @ vue.runtime.esm.js:5925
createChildren @ vue.runtime.esm.js:6053
createElm @ vue.runtime.esm.js:5954
createChildren @ vue.runtime.esm.js:6053
createElm @ vue.runtime.esm.js:5954
patch @ vue.runtime.esm.js:6477
Vue._update @ vue.runtime.esm.js:3945
updateComponent @ vue.runtime.esm.js:4066
get @ vue.runtime.esm.js:4479
Watcher @ vue.runtime.esm.js:4468
mountComponent @ vue.runtime.esm.js:4073
Vue.$mount @ vue.runtime.esm.js:8415
init @ vue.runtime.esm.js:3118
createComponent @ vue.runtime.esm.js:5978
createElm @ vue.runtime.esm.js:5925
createChildren @ vue.runtime.esm.js:6053
createElm @ vue.runtime.esm.js:5954
createChildren @ vue.runtime.esm.js:6053
createElm @ vue.runtime.esm.js:5954
addVnodes @ vue.runtime.esm.js:6106
updateChildren @ vue.runtime.esm.js:6233
patchVnode @ vue.runtime.esm.js:6319
updateChildren @ vue.runtime.esm.js:6193
patchVnode @ vue.runtime.esm.js:6319
updateChildren @ vue.runtime.esm.js:6193
patchVnode @ vue.runtime.esm.js:6319
updateChildren @ vue.runtime.esm.js:6193
patchVnode @ vue.runtime.esm.js:6319
patch @ vue.runtime.esm.js:6482
Vue._update @ vue.runtime.esm.js:3948
updateComponent @ vue.runtime.esm.js:4066
get @ vue.runtime.esm.js:4479
run @ vue.runtime.esm.js:4554
flushSchedulerQueue @ vue.runtime.esm.js:4310
eval @ vue.runtime.esm.js:1980
flushCallbacks @ vue.runtime.esm.js:1906
Promise.then (async)
timerFunc @ vue.runtime.esm.js:1933
nextTick @ vue.runtime.esm.js:1990
queueWatcher @ vue.runtime.esm.js:4402
update @ vue.runtime.esm.js:4544
notify @ vue.runtime.esm.js:730
reactiveSetter @ vue.runtime.esm.js:1055
proxySetter @ vue.runtime.esm.js:4631
expand @ VDataIterator.js:184
expand @ VDataIterator.js:197
click @ VDataTable.js:465
invokeWithErrorHandling @ vue.runtime.esm.js:1854
invoker @ vue.runtime.esm.js:2179
original._wrapper @ vue.runtime.esm.js:6917
Show 32 more frames
```

and

```
vue.runtime.esm.js:619 [Vue warn]: Error in render: "TypeError: Cannot read property 'transaction' of undefined"

found in

---> <HashLink> at src/components/helper/HashLink.vue
       <MovementLinks> at src/components/history/MovementLinks.vue
         <VCard>
           <VSimpleTable>
             <VData>
               <VDataTable>
                 <DataTable> at src/components/helper/DataTable.vue
                   <VSheet>
                     <VCard>
                       <DepositsWithdrawals> at src/views/history/DepositsWithdrawals.vue
                         <VTabItem>
                           <VTabsItems>
                             <VTabs>
                               <TabNavigation> at src/components/helper/TabNavigation.vue
                                 <History> at src/views/history/History.vue
                                   <VMain>
                                     <VApp>
                                       <App> at src/App.vue
                                         <Root>
warn @ vue.runtime.esm.js:619
logError @ vue.runtime.esm.js:1884
globalHandleError @ vue.runtime.esm.js:1879
handleError @ vue.runtime.esm.js:1839
Vue._render @ vue.runtime.esm.js:3550
updateComponent @ vue.runtime.esm.js:4066
get @ vue.runtime.esm.js:4479
Watcher @ vue.runtime.esm.js:4468
mountComponent @ vue.runtime.esm.js:4073
Vue.$mount @ vue.runtime.esm.js:8415
init @ vue.runtime.esm.js:3118
createComponent @ vue.runtime.esm.js:5978
createElm @ vue.runtime.esm.js:5925
createChildren @ vue.runtime.esm.js:6053
createElm @ vue.runtime.esm.js:5954
createChildren @ vue.runtime.esm.js:6053
createElm @ vue.runtime.esm.js:5954
patch @ vue.runtime.esm.js:6477
Vue._update @ vue.runtime.esm.js:3945
updateComponent @ vue.runtime.esm.js:4066
get @ vue.runtime.esm.js:4479
Watcher @ vue.runtime.esm.js:4468
mountComponent @ vue.runtime.esm.js:4073
Vue.$mount @ vue.runtime.esm.js:8415
init @ vue.runtime.esm.js:3118
createComponent @ vue.runtime.esm.js:5978
createElm @ vue.runtime.esm.js:5925
createChildren @ vue.runtime.esm.js:6053
createElm @ vue.runtime.esm.js:5954
createChildren @ vue.runtime.esm.js:6053
createElm @ vue.runtime.esm.js:5954
patch @ vue.runtime.esm.js:6477
Vue._update @ vue.runtime.esm.js:3945
updateComponent @ vue.runtime.esm.js:4066
get @ vue.runtime.esm.js:4479
Watcher @ vue.runtime.esm.js:4468
mountComponent @ vue.runtime.esm.js:4073
Vue.$mount @ vue.runtime.esm.js:8415
init @ vue.runtime.esm.js:3118
createComponent @ vue.runtime.esm.js:5978
createElm @ vue.runtime.esm.js:5925
createChildren @ vue.runtime.esm.js:6053
createElm @ vue.runtime.esm.js:5954
createChildren @ vue.runtime.esm.js:6053
createElm @ vue.runtime.esm.js:5954
addVnodes @ vue.runtime.esm.js:6106
updateChildren @ vue.runtime.esm.js:6233
patchVnode @ vue.runtime.esm.js:6319
updateChildren @ vue.runtime.esm.js:6193
patchVnode @ vue.runtime.esm.js:6319
updateChildren @ vue.runtime.esm.js:6193
patchVnode @ vue.runtime.esm.js:6319
updateChildren @ vue.runtime.esm.js:6193
patchVnode @ vue.runtime.esm.js:6319
patch @ vue.runtime.esm.js:6482
Vue._update @ vue.runtime.esm.js:3948
updateComponent @ vue.runtime.esm.js:4066
get @ vue.runtime.esm.js:4479
run @ vue.runtime.esm.js:4554
flushSchedulerQueue @ vue.runtime.esm.js:4310
eval @ vue.runtime.esm.js:1980
flushCallbacks @ vue.runtime.esm.js:1906
Promise.then (async)
timerFunc @ vue.runtime.esm.js:1933
nextTick @ vue.runtime.esm.js:1990
queueWatcher @ vue.runtime.esm.js:4402
update @ vue.runtime.esm.js:4544
notify @ vue.runtime.esm.js:730
reactiveSetter @ vue.runtime.esm.js:1055
proxySetter @ vue.runtime.esm.js:4631
expand @ VDataIterator.js:184
expand @ VDataIterator.js:197
click @ VDataTable.js:465
invokeWithErrorHandling @ vue.runtime.esm.js:1854
invoker @ vue.runtime.esm.js:2179
original._wrapper @ vue.runtime.esm.js:6917
Show 32 more frames
vue.runtime.esm.js:1888 TypeError: Cannot read property 'transaction' of undefined
    at VueComponent.get (HashLink.vue:109)
    at Watcher.get (vue.runtime.esm.js:4479)
    at Watcher.evaluate (vue.runtime.esm.js:4584)
    at VueComponent.computedGetter [as base] (vue.runtime.esm.js:4836)
    at VueComponent.get (HashLink.vue:134)
    at Watcher.get (vue.runtime.esm.js:4479)
    at Watcher.evaluate (vue.runtime.esm.js:4584)
    at VueComponent.computedGetter [as url] (vue.runtime.esm.js:4836)
    at Object.get (vue.runtime.esm.js:2072)
    at Proxy.render (eval at ./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/.cache/vue-loader","cacheIdentifier":"16fa182e-vue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js?!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/components/helper/HashLink.vue?vue&type=template&id=291cbd29&scoped=true& (app.js:2195), <anonymous>:191:72)
```

I think it's quite possible something missed in the recent develop changes done in https://github.com/rotki/rotki/commit/35968dcb431e094fecb9dc20b0f1a7eff3bd1ed8

## Task

Fix it.

**Comment by kelsos** [comment] 2021-03-22 13:11
I am unable to reproduce this issue. I am gonna close it. 

If you were running the development server without restarting it and switching between branches (development/master/bugfixes) then this is most probably a caching issue. Keep in mind that this can happen sometimes. I have complained some times about it in the past.

**Comment by LefterisJP** [comment] 2021-03-22 14:45
Let me check.

**Closed** 2021-03-22 16:15 UTC
Labels: frontend
