### ISSUE TITLE
Value in asset doesn't show correctly

### ISSUE THREAD

**Issue by stskeeps** [rotki/rotki#2653] opened 2021-03-27 16:48 UTC
## Problem Definition

I expected to see value of my owned assets (price * total owned = value) when entering Dashboard -> a particular asset 

Instead, I see Total owned, rounded down, as Value

Screenshots attached of a few examples:

![Screenshot 2021-03-27 at 17 47 32](https://user-images.githubusercontent.com/1255200/112727821-89e4cd00-8f24-11eb-8fac-f4ad1cc2169f.png)
![Screenshot 2021-03-27 at 17 47 19](https://user-images.githubusercontent.com/1255200/112727822-8bae9080-8f24-11eb-95b9-8716c52d1c04.png)
![Screenshot 2021-03-27 at 17 46 48](https://user-images.githubusercontent.com/1255200/112727823-8bae9080-8f24-11eb-9b72-fd49a613253d.png)
![Screenshot 2021-03-27 at 17 46 40](https://user-images.githubusercontent.com/1255200/112727825-8bae9080-8f24-11eb-9c1a-0c738418c955.png)

## Logs

I don't feel comfortable about providing logs as the issue is about values of certain portfolio associated with my github login (if need be can provide outside github)

### System Description

Operating system: MacOS 11.2.1
Rotki version: 1.15.2

**Comment by LefterisJP** [comment] 2021-03-27 18:33
Hey @stskeeps thanks a lot for the issue. As also discussed in discord closing this as a duplicate of https://github.com/rotki/rotki/issues/2628

**Closed by LefterisJP** 2021-03-27 18:33 UTC
