### ISSUE TITLE
Graph begins when Rotki first used not when assets purchased.

### ISSUE THREAD

**Issue by a7e8** [rotki/rotki#2514] opened 2021-03-08 09:37 UTC
## Problem Definition

I've noticed that the graph in the dashboard and for each asset begins when I first started using Rotki rather than when the assets where bought.

This doesn't really make sense. I think it's because I started by entering only manual balances. For assets that are supported like ETH I've updated to use blockchain balances.

I think the problem is that the balance graphs don't use the trading history (or blockchain history) to calculate balances.

**Comment by LefterisJP** [comment] 2021-03-08 09:42
Hey @a7e8 thanks for the issue. I am closing this as a duplicate of this: https://github.com/rotki/rotki/issues/1379

Historical data do indeed start from when the user started using rotki. Explanation is in that issue, and also the reason is explained and possible ways to provide additional graphs with additional data.

**Closed by LefterisJP** 2021-03-08 09:42 UTC
