### ISSUE TITLE
Bitcoin as Profit Currency

### ISSUE THREAD

**Issue by pluja** [rotki/rotki#1784] opened 2020-11-24 08:10 UTC
## Abstract

Currently Rotki only allows FIAT currencies as the 'Profit currency'. However I would like to see my total profits in BTC.

## Motivation

I don't really care about the $/€ value and I want to see the BTC value of my portfolio.

**Comment by LefterisJP** [comment] 2020-11-24 14:06
Hey @pluja thanks a lot for the issue. You are not the only one who has requested this. Quite a few have asked for it over the last months.

We already have an issue for it (generalized as any crypto): https://github.com/rotki/rotki/issues/1270

There is some technical difficulties we would need to address before implementing but am going to push it into a milestone so that we don't forget it's an important issue and many people want it.

I will also close this one as a duplicate of #1270

**Closed by LefterisJP** 2020-11-24 14:06 UTC
