### ISSUE TITLE
Microsoft Defender SmartScreen detects Rotki as malicious

### ISSUE THREAD

**Issue by aliask** [rotki/rotki#2365] opened 2021-02-13 00:33 UTC
## Problem Definition

Downloading a fresh copy of the 1.13.3 release Windows executable and attempting to run (after verifying SHA512) gives a Microsoft Defender SmartScreen prompt:
![image](https://user-images.githubusercontent.com/6219869/107835785-ce8e2c00-6dee-11eb-8ab4-9b110fa1f1c4.png)

It is possible to run the application by selecting "More info" and then "Run Anyway", however the message is disconcerting.

I suspect this is because the binary is not signed.

## Logs

N/A

### System Description
Operating system: Windows 10 (19041.746)
Rotki version: 1.13.3

**Comment by LefterisJP** [comment] 2021-02-13 00:39
Hello @aliask and thanks for using rotki.

This is true for all opensource applications in Windows, not just rotki.

We already have an issue to improve this: https://github.com/rotki/rotki/issues/1224
Closing this as duplicate of that other issue.

For more questions/discussion feel free to join our discord chat: https://discord.gg/aGCxHG7

**Closed by LefterisJP** 2021-02-13 00:39 UTC

**Comment by aliask** [comment] 2021-02-13 00:44
Sorry, I probably should have done a more in-depth search for duplicates, I tried defender & smartscreen and didn't find anything.
I haven't run into this message before, although admittedly I don't install "unusual" applications very often.

I think signing the binary should be a priority, it's a pretty bad first impression especially for the privacy/security conscious crypto crowd. Glad to see it's in the roadmap!
