### ISSUE TITLE
Trade History query warning

### ISSUE THREAD

**Issue by dankrad** [rotki/rotki#1821] opened 2020-11-27 01:16 UTC
These errors appeared when trying to create a tax report. Afterwards, the process seems to just have stopped and the numbers in the report window still reflected the previously generated report.

![Screenshot from 2020-11-27 01-13-23](https://user-images.githubusercontent.com/6130607/100400306-fa024580-304d-11eb-8bb7-39bd260de3cb.png)

Let me know what further info you would need to debug this

**Comment by LefterisJP** [comment] 2020-11-27 01:19
Hey @dankrad thanks a lot for the issue. Never seen this before. This seems like a symptom of something else.

Can you run rotki in debug mode (https://rotki.readthedocs.io/en/latest/contribute.html#id1), reproduce the problem, and then send us the log.

You can do it via discord DM: https://discord.gg/aGCxHG7 or email. Discord is easier for chatting also.

You can find the log's directory by going to Help -> Logs directory from the top meny.

**Comment by LefterisJP** [comment] 2021-05-08 10:18
Hey @dankrad apologies for not posting in this issue earlier.

So I had a look again at the 2 logs you emailed me and I can not see any error like this there. Additionally the version in the log is 1.9.0 which is a very old version (right now :sweat_smile: )

One of the 2 logs had no errors logged.
The other had a few funny timeouts when trying to access the rotki server, which should not really affect anything in the tax report. But nothing about loan_profit access of an undefined object. This is what I would like to figure out how it could happen.

No other user has seen this error so I am wondering if it's something specific in your settings and setup.
Does it happen also with newer version?

If not can we close this issue?

**Comment by kelsos** [comment] 2021-05-10 07:03
@LefterisJP yes you wouldn't see the error in the backend logs since the `loan_profit` of an undefined object is a frontend error. This essentially means that in the response the frontend received the `overview` was not defined.

**Comment by LefterisJP** [comment] 2023-01-23 12:19
I am closing as it's for too old a rotki version and we already got a request from dankrad pending about the bed & breakfast rule

**Closed by LefterisJP** 2023-01-23 12:19 UTC
