### ISSUE TITLE
Show proper error to user if Coinbase is not setup with access to all accounts

### ISSUE THREAD

**Issue by ChosunOne** [rotki/rotki#1014] opened 2020-05-20 16:07 UTC
## Problem Definition

Attempting to setup Rotki with a coinbase api key and secret fails.  I created a key with read only access and I am getting a timeout error 30s after clicking setup.  Below are the exact permissions enabled:
API Version: 2019-09-13
Accounts: 
```
ETH Wallet
```
Permissions:
```
wallet:accounts:read 
wallet:addresses:read 
wallet:buys:read 
wallet:checkouts:read 
wallet:deposits:read 
wallet:orders:read 
wallet:sells:read 
wallet:trades:read 
wallet:transactions:read 
wallet:withdrawals:read
```

### System Description
Ubuntu 20.04
Linux 5.4.0-31-generic #35-Ubuntu SMP Thu May 7 20:20:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Comments
Perhaps it would be better to use OAuth for Coinbase than creating an API Key and secret?  I think you could explicitly state the permissions you need that way.

**Comment by LefterisJP** [comment] 2020-05-20 16:16
Hey @ChosunOne thanks for the issue!

Rotki does not work with specific wallet permissions for coinbase. You should allow read access to all. I assume this is what the problem is.
Here is a screenshot of how permissions should look like:

![2020-05-20-181259_525x783_scrot](https://user-images.githubusercontent.com/1658405/82470426-9c50d780-9ac5-11ea-99f4-685e1afc8f18.png)

Can you try and tell me if it works like that?

If it does, still I guess we should somehow see if a better error can be shown. Timing out after 30 seconds is not good.

> Perhaps it would be better to use OAuth for Coinbase than creating an API Key and secret? I think you could explicitly state the permissions you need that way.

Would not have any advantages and it would be hard since it would be extra work (and a lot of it) for just one exchange. Special cases like that make for a hard to maintain system.

**Comment by ChosunOne** [comment] 2020-05-20 16:35
Ok enabling permissions for all wallets worked, thank you!  Probably worth putting a notice or something in the app to indicate it needs all wallets for coinbase.

**Comment by LefterisJP** [comment] 2020-05-20 16:58
@ChosunOne Definitely. Will keep the issue open until that notice is added. Will also try to see if we can show an error if the permissions are wrong like that.

**Comment by LefterisJP** [comment] 2020-05-21 19:42
Hey @ChosunOne so I am a bit puzzled here. I tried to reproduce your error with coinbase setup with a key with just a random wallet and not "all wallets".

It does not happen for me. I made multiple new keys and tried many different wallets but I never got a timeout issue. Perhaps coinbase was having API problems for that exact moment when you tried to connect your rotki account with it?

Found some minor things missing from the setup error due to permissions message: https://github.com/rotki/rotki/pull/1023

But that's it.

**Comment by ChosunOne** [comment] 2020-05-21 21:16
I suppose it's entirely possible, though there was no indication of any api issues I could see on coinbase at the time. As it seems to be working for me now I don't feel strongly about future work in this area. At the very least if others report issues we have a potential fix in enabling all accounts on the api key.

**Comment by LefterisJP** [comment] 2020-05-21 22:20
Thanks :+1:

Will close this issue for now then and see how if anyone else experiences something similar. In that case will have to debug with more logs.

**Closed by LefterisJP** 2020-05-21 22:20 UTC
