### ISSUE TITLE
Rotki failed to start

### ISSUE THREAD

**Issue by Blackswan122** [rotki/rotki#2800] opened 2021-04-27 18:36 UTC
I tried to start Rotki but it said update first which i did top right on trying to login. inow get an error.

Failed to start rotkehlchen backend:
Traceback (most recent call last):
  File "rotkehlchen\__main__.py", line 18, in main
  File "rotkehlchen\server.py", line 30, in __init__
  File "rotkehlchen\rotkehlchen.py", line 147, in __init__
  File "rotkehlchen\globaldb\handler.py", line 110, in __new__
  File "rotkehlchen\globaldb\handler.py", line 78, in _initialize_global_db_directory
  File "rotkehlchen\globaldb\handler.py", line 60, in _initialize_globaldb
  File "rotkehlchen\globaldb\upgrades\v1_v2.py", line 16, in upgrade_ethereum_asset_ids
sqlite3.OperationalError: no such column: B.name

I've no idea what's happening but I haven't managed to login at all today. At first I thought it was a backend office problem

**Comment by LefterisJP** [comment] 2021-04-27 19:01
hey @Blackswan122 

Did you use rotki v1.16.0 before? And now you suddenly started getting this?

If that's the case I am 99% sure you tried to open rotki with v1.15.2 again after having upgraded to rotki v1.16.0.

I mentioned that this is a breaking prolem in discord: https://discord.com/channels/657906918408585217/657906918961971212/835286413985054721

And there in the link you can find the ways to fix this if you do this. Please let me know if that's the case.

**Comment by yabirgb** [comment] 2021-04-27 19:56
Yes I can confirm that this error happened at least to me after going back to 1.15.2 from 1.16.0

**Comment by LefterisJP** [comment] 2021-04-27 19:57
yes this is the reason why I posted this in discord general so people don't do this mistake and why I added this: https://github.com/rotki/rotki/pull/2782

This protective check should have been added there already in v1.16.0 but we did not think of this, so it will only work for later versions.

**Comment by LefterisJP** [comment] 2021-04-27 20:24
Just for documentation sake posting it here too:

To fix it you would need to go to the rotki directory:

Linux: `~/.local/share/rotki/data/global_data/`   MacOS: `~/Library/Application Support/rotki/data`  Windows: `%APPDATA%\rotki\data`

And either:

1. Delete global.db.   -> **warning** all custom assets input by you and all price caches would be deleted.
2. Go in with sqlite and edit 1 field. In Linux you would do it like this:
    ```sqlite3 global.db
SQLite version 3.35.3 2021-03-26 12:12:52
Enter ".help" for usage hints.
sqlite> INSERT OR REPLACE INTO SETTINGS(name, value) VALUES("version", 2);
```

Best solution is (2) by far since you would lose no data.

**Comment by LefterisJP** [comment] 2021-04-28 08:53
Closing the issue. The user did (2) with our help in discord.

**Closed by LefterisJP** 2021-04-28 08:53 UTC
