### ISSUE TITLE
Failing to start due to backend error

### ISSUE THREAD

**Issue by dlg95** [rotki/rotki#5886] opened 2023-04-12 10:34 UTC
## Problem Definition

I'm getting this message trying to start rotki:

[rotki-core] [rotki-core] Failed to start rotki backend:
Traceback (most recent call last):
  File "rotkehlchen/globaldb/upgrades/manager.py", line 85, in maybe_upgrade_globaldb
  File "rotkehlchen/globaldb/upgrades/v3_v4.py", line 388, in migrate_to_v4
  File "rotkehlchen/globaldb/upgrades/v3_v4.py", line 359, in _upgrade_address_book_table
  File "rotkehlchen/db/drivers/gevent.py", line 89, in execute
sqlite3.OperationalError: no such table: address_book

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "rotkehlchen/__main__.py", line 17, in main
  File "rotkehlchen/server.py", line 32, in __init__
  File "rotkehlchen/rotkehlchen.py", line 150, in __init__
  File "rotkehlchen/globaldb/handler.py", line 212, in __new__
  File "rotkehlchen/globaldb/handler.py", line 178, in _initialize_global_db_directory
  File "rotkehlchen/globaldb/handler.py", line 143, in initialize_globaldb
  File "rotkehlchen/globaldb/upgrades/manager.py", line 94, in maybe_upgrade_globaldb
ValueError: Failed at global DB upgrade from version 3 to 4: no such table: address_book

##logs
Excerpt from rotkehlchen.log:
[29/03/2022 15:04:27 CEST] INFO rotkehlchen.rotkehlchen Greenlet-0: User successfully logged out user=dlg95
[29/03/2022 15:04:27 CEST] DEBUG rotkehlchen.api.rest Greenlet-0: Waiting for greenlets
[29/03/2022 15:04:27 CEST] DEBUG rotkehlchen.api.rest Greenlet-0: Waited for greenlets. Killing all other greenlets
[29/03/2022 15:04:27 CEST] DEBUG rotkehlchen.api.rest Greenlet-0: Greenlets killed. Killing zerorpc greenlet
[29/03/2022 15:04:27 CEST] DEBUG rotkehlchen.api.rest Greenlet-0: Shutdown completed
[10/04/2023 19:36:23 +07] DEBUG rotkehlchen.globaldb.upgrades.v2_v3 Entered globaldb v2->v3 upgrade
[10/04/2023 19:36:23 +07] DEBUG rotkehlchen.globaldb.upgrades.v2_v3 Obtain ethereum assets information
[10/04/2023 19:36:23 +07] DEBUG rotkehlchen.globaldb.upgrades.v2_v3 Upgrade other and owned assets
[10/04/2023 19:36:23 +07] DEBUG rotkehlchen.globaldb.upgrades.v2_v3 Upgrade prices
[10/04/2023 19:36:23 +07] DEBUG rotkehlchen.globaldb.upgrades.v2_v3 Upgrade binance pairs
[10/04/2023 19:36:23 +07] DEBUG rotkehlchen.globaldb.upgrades.v2_v3 Purge/delete tables with outdated information
[10/04/2023 19:36:23 +07] DEBUG rotkehlchen.globaldb.upgrades.v2_v3 Create new tables
[10/04/2023 19:36:23 +07] DEBUG rotkehlchen.globaldb.upgrades.v2_v3 Input common asset data
[10/04/2023 19:36:23 +07] DEBUG rotkehlchen.globaldb.upgrades.v2_v3 Input asset data
[10/04/2023 19:36:23 +07] DEBUG rotkehlchen.globaldb.upgrades.v2_v3 Input prices
[10/04/2023 19:36:23 +07] DEBUG rotkehlchen.globaldb.upgrades.v2_v3 Input binance pairs
[10/04/2023 19:36:23 +07] DEBUG rotkehlchen.globaldb.upgrades.v2_v3 Input evm and underlying tokens
[10/04/2023 19:36:23 +07] DEBUG rotkehlchen.globaldb.upgrades.v2_v3 Finished globaldb v2->v3 upgrade
[10/04/2023 19:36:23 +07] DEBUG rotkehlchen.globaldb.upgrades.v3_v4 Main Greenlet: Entered globaldb v3->v4 upgrade
[10/04/2023 19:36:23 +07] DEBUG rotkehlchen.globaldb.upgrades.v3_v4 Main Greenlet: Enter _create_new_tables
[10/04/2023 19:36:23 +07] DEBUG rotkehlchen.globaldb.upgrades.v3_v4 Main Greenlet: Exit _create_new_tables
[10/04/2023 19:36:23 +07] DEBUG rotkehlchen.globaldb.upgrades.v3_v4 Main Greenlet: Enter _add_eth_abis_json
[10/04/2023 19:36:23 +07] DEBUG rotkehlchen.globaldb.upgrades.v3_v4 Main Greenlet: Exit _add_eth_abis_json
[10/04/2023 19:36:23 +07] DEBUG rotkehlchen.globaldb.upgrades.v3_v4 Main Greenlet: Enter _add_eth_contracts_json
[10/04/2023 19:36:23 +07] DEBUG rotkehlchen.globaldb.upgrades.v3_v4 Main Greenlet: Exit _add_eth_contracts_json
[10/04/2023 19:36:23 +07] DEBUG rotkehlchen.globaldb.upgrades.v3_v4 Main Greenlet: Enter _add_optimism_contracts
[10/04/2023 19:36:23 +07] DEBUG rotkehlchen.globaldb.upgrades.v3_v4 Main Greenlet: Exit _add_optimism_contracts
[10/04/2023 19:36:23 +07] DEBUG rotkehlchen.globaldb.upgrades.v3_v4 Main Greenlet: Enter _populate_asset_collection
[10/04/2023 19:36:23 +07] DEBUG rotkehlchen.globaldb.upgrades.v3_v4 Main Greenlet: Exit _populate_asset_collection
[10/04/2023 19:36:23 +07] DEBUG rotkehlchen.globaldb.upgrades.v3_v4 Main Greenlet: Enter _populate_multiasset_mappings
[10/04/2023 19:36:23 +07] DEBUG rotkehlchen.globaldb.upgrades.v3_v4 Main Greenlet: Exit _populate_multiasset_mappings
[10/04/2023 19:36:23 +07] ERROR rotkehlchen.globaldb.upgrades.manager Main Greenlet: Failed at global DB upgrade from version 3 to 4: no such table: address_book
[10/04/2023 19:36:23 +07] CRITICAL root Traceback (most recent call last):
  File "rotkehlchen/globaldb/upgrades/manager.py", line 85, in maybe_upgrade_globaldb
  File "rotkehlchen/globaldb/upgrades/v3_v4.py", line 388, in migrate_to_v4
  File "rotkehlchen/globaldb/upgrades/v3_v4.py", line 359, in _upgrade_address_book_table
  File "rotkehlchen/db/drivers/gevent.py", line 89, in execute
sqlite3.OperationalError: no such table: address_book

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "rotkehlchen/__main__.py", line 17, in main
  File "rotkehlchen/server.py", line 32, in __init__
  File "rotkehlchen/rotkehlchen.py", line 150, in __init__
  File "rotkehlchen/globaldb/handler.py", line 212, in __new__
  File "rotkehlchen/globaldb/handler.py", line 178, in _initialize_global_db_directory
  File "rotkehlchen/globaldb/handler.py", line 143, in initialize_globaldb
  File "rotkehlchen/globaldb/upgrades/manager.py", line 94, in maybe_upgrade_globaldb
ValueError: Failed at global DB upgrade from version 3 to 4: no such table: address_book

[12/04/2023 14:10:51 +07] DEBUG rotkehlchen.globaldb.upgrades.v3_v4 Main Greenlet: Entered globaldb v3->v4 upgrade
[12/04/2023 14:10:51 +07] DEBUG rotkehlchen.globaldb.upgrades.v3_v4 Main Greenlet: Enter _create_new_tables
[12/04/2023 14:10:51 +07] DEBUG rotkehlchen.globaldb.upgrades.v3_v4 Main Greenlet: Exit _create_new_tables
[12/04/2023 14:10:51 +07] DEBUG rotkehlchen.globaldb.upgrades.v3_v4 Main Greenlet: Enter _add_eth_abis_json
[12/04/2023 14:10:51 +07] DEBUG rotkehlchen.globaldb.upgrades.v3_v4 Main Greenlet: Exit _add_eth_abis_json
[12/04/2023 14:10:51 +07] DEBUG rotkehlchen.globaldb.upgrades.v3_v4 Main Greenlet: Enter _add_eth_contracts_json
[12/04/2023 14:10:51 +07] DEBUG rotkehlchen.globaldb.upgrades.v3_v4 Main Greenlet: Exit _add_eth_contracts_json
[12/04/2023 14:10:51 +07] DEBUG rotkehlchen.globaldb.upgrades.v3_v4 Main Greenlet: Enter _add_optimism_contracts
[12/04/2023 14:10:51 +07] DEBUG rotkehlchen.globaldb.upgrades.v3_v4 Main Greenlet: Exit _add_optimism_contracts
[12/04/2023 14:10:51 +07] DEBUG rotkehlchen.globaldb.upgrades.v3_v4 Main Greenlet: Enter _populate_asset_collection
[12/04/2023 14:10:51 +07] DEBUG rotkehlchen.globaldb.upgrades.v3_v4 Main Greenlet: Exit _populate_asset_collection
[12/04/2023 14:10:51 +07] DEBUG rotkehlchen.globaldb.upgrades.v3_v4 Main Greenlet: Enter _populate_multiasset_mappings
[12/04/2023 14:10:51 +07] DEBUG rotkehlchen.globaldb.upgrades.v3_v4 Main Greenlet: Exit _populate_multiasset_mappings
[12/04/2023 14:10:51 +07] ERROR rotkehlchen.globaldb.upgrades.manager Main Greenlet: Failed at global DB upgrade from version 3 to 4: no such table: address_book
[12/04/2023 14:10:51 +07] CRITICAL root Traceback (most recent call last):
  File "rotkehlchen/globaldb/upgrades/manager.py", line 85, in maybe_upgrade_globaldb
  File "rotkehlchen/globaldb/upgrades/v3_v4.py", line 388, in migrate_to_v4
  File "rotkehlchen/globaldb/upgrades/v3_v4.py", line 359, in _upgrade_address_book_table
  File "rotkehlchen/db/drivers/gevent.py", line 89, in execute
sqlite3.OperationalError: no such table: address_book

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "rotkehlchen/__main__.py", line 17, in main
  File "rotkehlchen/server.py", line 32, in __init__
  File "rotkehlchen/rotkehlchen.py", line 150, in __init__
  File "rotkehlchen/globaldb/handler.py", line 212, in __new__
  File "rotkehlchen/globaldb/handler.py", line 178, in _initialize_global_db_directory
  File "rotkehlchen/globaldb/handler.py", line 143, in initialize_globaldb
  File "rotkehlchen/globaldb/upgrades/manager.py", line 94, in maybe_upgrade_globaldb
ValueError: Failed at global DB upgrade from version 3 to 4: no such table: address_book

[12/04/2023 17:24:10 +07] DEBUG rotkehlchen.globaldb.upgrades.v3_v4 Main Greenlet: Entered globaldb v3->v4 upgrade
[12/04/2023 17:24:10 +07] DEBUG rotkehlchen.globaldb.upgrades.v3_v4 Main Greenlet: Enter _create_new_tables
[12/04/2023 17:24:10 +07] DEBUG rotkehlchen.globaldb.upgrades.v3_v4 Main Greenlet: Exit _create_new_tables
[12/04/2023 17:24:10 +07] DEBUG rotkehlchen.globaldb.upgrades.v3_v4 Main Greenlet: Enter _add_eth_abis_json
[12/04/2023 17:24:10 +07] DEBUG rotkehlchen.globaldb.upgrades.v3_v4 Main Greenlet: Exit _add_eth_abis_json
[12/04/2023 17:24:10 +07] DEBUG rotkehlchen.globaldb.upgrades.v3_v4 Main Greenlet: Enter _add_eth_contracts_json
[12/04/2023 17:24:10 +07] DEBUG rotkehlchen.globaldb.upgrades.v3_v4 Main Greenlet: Exit _add_eth_contracts_json
[12/04/2023 17:24:10 +07] DEBUG rotkehlchen.globaldb.upgrades.v3_v4 Main Greenlet: Enter _add_optimism_contracts
[12/04/2023 17:24:10 +07] DEBUG rotkehlchen.globaldb.upgrades.v3_v4 Main Greenlet: Exit _add_optimism_contracts
[12/04/2023 17:24:10 +07] DEBUG rotkehlchen.globaldb.upgrades.v3_v4 Main Greenlet: Enter _populate_asset_collection
[12/04/2023 17:24:10 +07] DEBUG rotkehlchen.globaldb.upgrades.v3_v4 Main Greenlet: Exit _populate_asset_collection
[12/04/2023 17:24:10 +07] DEBUG rotkehlchen.globaldb.upgrades.v3_v4 Main Greenlet: Enter _populate_multiasset_mappings
[12/04/2023 17:24:10 +07] DEBUG rotkehlchen.globaldb.upgrades.v3_v4 Main Greenlet: Exit _populate_multiasset_mappings
[12/04/2023 17:24:10 +07] ERROR rotkehlchen.globaldb.upgrades.manager Main Greenlet: Failed at global DB upgrade from version 3 to 4: no such table: address_book
[12/04/2023 17:24:10 +07] CRITICAL root Traceback (most recent call last):
  File "rotkehlchen/globaldb/upgrades/manager.py", line 85, in maybe_upgrade_globaldb
  File "rotkehlchen/globaldb/upgrades/v3_v4.py", line 388, in migrate_to_v4
  File "rotkehlchen/globaldb/upgrades/v3_v4.py", line 359, in _upgrade_address_book_table
  File "rotkehlchen/db/drivers/gevent.py", line 89, in execute
sqlite3.OperationalError: no such table: address_book

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "rotkehlchen/__main__.py", line 17, in main
  File "rotkehlchen/server.py", line 32, in __init__
  File "rotkehlchen/rotkehlchen.py", line 150, in __init__
  File "rotkehlchen/globaldb/handler.py", line 212, in __new__
  File "rotkehlchen/globaldb/handler.py", line 178, in _initialize_global_db_directory
  File "rotkehlchen/globaldb/handler.py", line 143, in initialize_globaldb
  File "rotkehlchen/globaldb/upgrades/manager.py", line 94, in maybe_upgrade_globaldb
ValueError: Failed at global DB upgrade from version 3 to 4: no such table: address_book

[12/04/2023 17:28:35 +07] DEBUG rotkehlchen.globaldb.upgrades.v3_v4 Main Greenlet: Entered globaldb v3->v4 upgrade
[12/04/2023 17:28:35 +07] DEBUG rotkehlchen.globaldb.upgrades.v3_v4 Main Greenlet: Enter _create_new_tables
[12/04/2023 17:28:35 +07] DEBUG rotkehlchen.globaldb.upgrades.v3_v4 Main Greenlet: Exit _create_new_tables
[12/04/2023 17:28:35 +07] DEBUG rotkehlchen.globaldb.upgrades.v3_v4 Main Greenlet: Enter _add_eth_abis_json
[12/04/2023 17:28:35 +07] DEBUG rotkehlchen.globaldb.upgrades.v3_v4 Main Greenlet: Exit _add_eth_abis_json
[12/04/2023 17:28:35 +07] DEBUG rotkehlchen.globaldb.upgrades.v3_v4 Main Greenlet: Enter _add_eth_contracts_json
[12/04/2023 17:28:35 +07] DEBUG rotkehlchen.globaldb.upgrades.v3_v4 Main Greenlet: Exit _add_eth_contracts_json
[12/04/2023 17:28:35 +07] DEBUG rotkehlchen.globaldb.upgrades.v3_v4 Main Greenlet: Enter _add_optimism_contracts
[12/04/2023 17:28:35 +07] DEBUG rotkehlchen.globaldb.upgrades.v3_v4 Main Greenlet: Exit _add_optimism_contracts
[12/04/2023 17:28:35 +07] DEBUG rotkehlchen.globaldb.upgrades.v3_v4 Main Greenlet: Enter _populate_asset_collection
[12/04/2023 17:28:35 +07] DEBUG rotkehlchen.globaldb.upgrades.v3_v4 Main Greenlet: Exit _populate_asset_collection
[12/04/2023 17:28:35 +07] DEBUG rotkehlchen.globaldb.upgrades.v3_v4 Main Greenlet: Enter _populate_multiasset_mappings
[12/04/2023 17:28:35 +07] DEBUG rotkehlchen.globaldb.upgrades.v3_v4 Main Greenlet: Exit _populate_multiasset_mappings
[12/04/2023 17:28:35 +07] ERROR rotkehlchen.globaldb.upgrades.manager Main Greenlet: Failed at global DB upgrade from version 3 to 4: no such table: address_book
[12/04/2023 17:28:35 +07] CRITICAL root Traceback (most recent call last):
  File "rotkehlchen/globaldb/upgrades/manager.py", line 85, in maybe_upgrade_globaldb
  File "rotkehlchen/globaldb/upgrades/v3_v4.py", line 388, in migrate_to_v4
  File "rotkehlchen/globaldb/upgrades/v3_v4.py", line 359, in _upgrade_address_book_table
  File "rotkehlchen/db/drivers/gevent.py", line 89, in execute
sqlite3.OperationalError: no such table: address_book

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "rotkehlchen/__main__.py", line 17, in main
  File "rotkehlchen/server.py", line 32, in __init__
  File "rotkehlchen/rotkehlchen.py", line 150, in __init__
  File "rotkehlchen/globaldb/handler.py", line 212, in __new__
  File "rotkehlchen/globaldb/handler.py", line 178, in _initialize_global_db_directory
  File "rotkehlchen/globaldb/handler.py", line 143, in initialize_globaldb
  File "rotkehlchen/globaldb/upgrades/manager.py", line 94, in maybe_upgrade_globaldb
ValueError: Failed at global DB upgrade from version 3 to 4: no such table: address_book

##rotki_electron.log:

2023-04-12T10:24:06.316Z: 
    ------------------
    | Starting rotki |
    ------------------
2023-04-12T10:24:08.053Z: Restarting the backend
2023-04-12T10:24:08.061Z: Determining if we are packaged by seeing if /Applications/rotki.app/Contents/Resources/backend/rotki-core exists
2023-04-12T10:24:08.063Z: Starting packaged python subprocess: /Applications/rotki.app/Contents/Resources/backend/rotki-core/rotki-core-1.27.1-macos --rest-api-port 4242 --api-cors app://* --logfile /Users/danielglauert/Library/Application Support/rotki/logs/rotkehlchen.log
2023-04-12T10:24:08.065Z: The Python sub-process started on port: 4242 (PID: 64858)
2023-04-12T10:24:10.900Z: [rotki-core] 
2023-04-12T10:24:10.901Z: [rotki-core] Failed to start rotki backend:
Traceback (most recent call last):
  File "rotkehlchen/globaldb/upgrades/manager.py", line 85, in maybe_upgrade_globaldb
  File "rotkehlchen/globaldb/upgrades/v3_v4.py", line 388, in migrate_to_v4
  File "rotkehlchen/globaldb/upgrades/v3_v4.py", line 359, in _upgrade_address_book_table
  File "rotkehlchen/db/drivers/gevent.py", line 89, in execute
sqlite3.OperationalError: no such table: address_book

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "rotkehlchen/__main__.py", line 17, in main
  File "rotkehlchen/server.py", line 32, in __init__
  File "rotkehlchen/rotkehlchen.py", line 150, in __init__
  File "rotkehlchen/globaldb/handler.py", line 212, in __new__
  File "rotkehlchen/globaldb/handler.py", line 178, in _initialize_global_db_directory
  File "rotkehlchen/globaldb/handler.py", line 143, in initialize_globaldb
  File "rotkehlchen/globaldb/upgrades/manager.py", line 94, in maybe_upgrade_globaldb
ValueError: Failed at global DB upgrade from version 3 to 4: no such table: address_book

2023-04-12T10:24:10.902Z: The Python sub-process exited with signal: null (Code: 1)
2023-04-12T10:24:35.005Z: Terminating the backend
2023-04-12T10:28:31.541Z: 
    ------------------
    | Starting rotki |
    ------------------
2023-04-12T10:28:33.099Z: Restarting the backend
2023-04-12T10:28:33.108Z: Determining if we are packaged by seeing if /Applications/rotki.app/Contents/Resources/backend/rotki-core exists
2023-04-12T10:28:33.109Z: Starting packaged python subprocess: /Applications/rotki.app/Contents/Resources/backend/rotki-core/rotki-core-1.27.1-macos --rest-api-port 4242 --api-cors app://* --logfile /Users/danielglauert/Library/Application Support/rotki/logs/rotkehlchen.log
2023-04-12T10:28:33.111Z: The Python sub-process started on port: 4242 (PID: 64967)
2023-04-12T10:28:36.129Z: [rotki-core] 
2023-04-12T10:28:36.130Z: [rotki-core] Failed to start rotki backend:
Traceback (most recent call last):
  File "rotkehlchen/globaldb/upgrades/manager.py", line 85, in maybe_upgrade_globaldb
  File "rotkehlchen/globaldb/upgrades/v3_v4.py", line 388, in migrate_to_v4
  File "rotkehlchen/globaldb/upgrades/v3_v4.py", line 359, in _upgrade_address_book_table
  File "rotkehlchen/db/drivers/gevent.py", line 89, in execute
sqlite3.OperationalError: no such table: address_book

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "rotkehlchen/__main__.py", line 17, in main
  File "rotkehlchen/server.py", line 32, in __init__
  File "rotkehlchen/rotkehlchen.py", line 150, in __init__
  File "rotkehlchen/globaldb/handler.py", line 212, in __new__
  File "rotkehlchen/globaldb/handler.py", line 178, in _initialize_global_db_directory
  File "rotkehlchen/globaldb/handler.py", line 143, in initialize_globaldb
  File "rotkehlchen/globaldb/upgrades/manager.py", line 94, in maybe_upgrade_globaldb
ValueError: Failed at global DB upgrade from version 3 to 4: no such table: address_book

2023-04-12T10:28:36.130Z: The Python sub-process exited with signal: null (Code: 1)

Operating system: MacOS 13.2.1
Rotki version:

**Comment by yabirgb** [comment] 2023-04-12 10:47
Hello @dlg95 ! Thanks for reporting this to us. Is a duplicate of https://github.com/rotki/rotki/issues/5871 and is already fixed but the fix will come in the next release unfortunately. If you join our discord we can help you to fix it by manually editing your database  https://discord.gg/aGCxHG7. Have DMs open since there is a captcha challenge

There is also a solution posted here in case you want to go with it https://github.com/rotki/rotki/issues/5871#issuecomment-1498761779

The fix to avoid such an error on our side in the future is here https://github.com/rotki/rotki/pull/5872

**Comment by dlg95** [comment] 2023-04-12 13:43
Thank you, awesome work you do!

**Comment by LefterisJP** [comment] 2023-04-12 14:49
> Thank you, awesome work you do!

Did it work friend? If yes can we close the issue?

**Comment by dlg95** [comment] 2023-04-12 14:54
Yes, it worked! You can close the issue. 🙏

**Closed** 2023-04-12 14:55 UTC
