### ISSUE TITLE
Exchange rate error 

### ISSUE THREAD

**Issue by drgonzo31** [rotki/rotki#2792] opened 2021-04-25 22:54 UTC
## Problem Definition
On starting Rotki, I encounter this error
"Failed fetching exchange rates: {"currencies": {"17": ["Unknown asset NOK provided."]}}"
The dashboard area with percentage change is blank. In the assets area when I change the currency "prices in XXX" title changes to that currency but the value for each asset doesn't change from its USD value.

### System Description

Operating system:  Linux and Windows
Rotki version: v1.16.0.

**Comment by LefterisJP** [comment] 2021-04-26 07:19
Hey @drgonzo31 thanks for the issue. Did you by any chance delete the NOK currency when playing with the asset manager? What did you do to cause this to happen?

**Comment by drgonzo31** [comment] 2021-04-26 07:32
Hey @LefterisJP,
No I didn't delete the NOK currency. This started after upgrading Rotki on the windows platform from Rotki v1.15.1.

Regards
Dylan

**Comment by LefterisJP** [comment] 2021-04-26 07:41
Hmmm do you use rotki in both windows and linux? And how do you share the use DB between the two? What happened during the update to v1.16.0? Any conflicts? How did you resolve them? Anything special in the logs? Did you restart rotki after updating?

 Can you share with us here the global.db from windows? It's a big file. But it contains absolutely no user data, just the assets used by rotki.

For Windows it should be in `%LOCALAPPDATA%/rotki/data/global_data/global.db`.

**Comment by drgonzo31** [comment] 2021-04-28 04:57
>Hmmm do you use rotki in both windows and linux? 
I was using it primarily on a windows system. The problem started on windows. I then moved the data folder over to my linux system with a fresh install of latest Rotki. The problem continued onto the linux system.

> And how do you share the user DB between the two?
I copied the data folder %LOCALAPPDATA%/rotki/data on the windows system to the linux data folder ~/.local/share/rotki/data/
> What happened during the update to v1.16.0? Any conflicts? How did you resolve them? Anything special in the logs? Did you restart rotki after updating?
The only issues I noticed were the same with the previous update. I have some iconomi assets it doesn't support and the NOK currency error.
>Can you share with us here the global.db from windows? It's a big file. But it contains absolutely no user data, just the assets used by rotki.
[global.zip](https://github.com/rotki/rotki/files/6389171/global.zip)


Regards
Dylan

**Comment by LefterisJP** [comment] 2021-04-28 07:37
Hey Dylan. All right this is helpful.

## The problem

The problem is in that global DB. It's missing the 2 fiat assets that were added in v1.15.1. I am not 100% sure why/how that could have happened. I have a theory (read below)

#### Your global.db

```
sqlite> SELECT * from assets where type='A';
AUD|A|Australian Dollar|AUD|||||AUD
NZD|A|New Zealand Dollar|NZD|||||NZD
BRL|A|Brazilian Real|BRL|||||BRL
CAD|A|Canadian Dollar|CAD|||||CAD
CHF|A|Swiss Franc|CHF|||||CHF
CNY|A|Chinese Yuan|CNY|||||CNY
EUR|A|Euro|EUR|915148800||||EUR
GBP|A|Great British Pound|GBP|||||GBP
JPY|A|Japanese Yen|JPY|||||JPY
KRW|A|Korean won|KRW|||||KRW
RUB|A|Russian Ruble|RUB|||||RUB
TRY|A|Turkish Lyra|TRY|||trias||TRY
USD|A|United States Dollar|USD|||||USD
ZAR|A|South African Rand|ZAR|||||ZAR
TWD|A|New Taiwan Dollar|TWD|||||TWD
SGD|A|Singapore Dollar|SGD|||||SGD
SEK|A|Swedish Krona|SEK|||||SEK
```

#### A normal v1.16.0 global.db

```
sqlite> SELECT * from assets where type='A';
AUD|A|Australian Dollar|AUD|||||AUD
NZD|A|New Zealand Dollar|NZD|||||NZD
BRL|A|Brazilian Real|BRL|||||BRL
CAD|A|Canadian Dollar|CAD|||||CAD
CHF|A|Swiss Franc|CHF|||||CHF
CNY|A|Chinese Yuan|CNY|||||CNY
EUR|A|Euro|EUR|915148800||||EUR
GBP|A|Great British Pound|GBP|||||GBP
JPY|A|Japanese Yen|JPY|||||JPY
KRW|A|Korean won|KRW|||||KRW
NOK|A|Norwegian krone|NOK|||||NOK
RUB|A|Russian Ruble|RUB|||||RUB
TRY|A|Turkish Lyra|TRY|||trias||TRY
USD|A|United States Dollar|USD|||||USD
ZAR|A|South African Rand|ZAR|||||ZAR
TWD|A|New Taiwan Dollar|TWD|||||TWD
SGD|A|Singapore Dollar|SGD|||||SGD
SEK|A|Swedish Krona|SEK|||||SEK
sqlite> 
```

### More info

Can you tell me from which version did you upgrade? Did you by any chance go directly from v1.15.0 to v1.16.0 skipping v1.151. and v1.15.2? I can see it happening then.

## Solution

The solution is simple if you don't have any custom assets in the global.db. You just need to close the app, delete the global.db and then open the app again. It will be recreated with all v1.16.0 assets. If you have custom assets you can go in your global DB and add the missing assets with sql statements. I can help with this if it's needed. Just let me know.

Most importantly I would like to know what I asked in "More Info". It will really help us know how/what happened.

**Comment by drgonzo31** [comment] 2021-04-28 07:54
> More info
Can you tell me from which version did you upgrade? Did you by any chance go directly from v1.15.0 to v1.16.0 skipping v1.151. and v1.15.2? I can see it happening then.

I went from v1.50.0 (windows) to one of the v1.15.1 (windows) then to the v1.16.0 (windows) then copied data folder to v1.16.0 (linux).

**Comment by drgonzo31** [comment] 2021-04-28 08:18
> The solution is simple if you don't have any custom assets in the global.db. You just need to close the app, delete the global.db and then open the app again. 

That did the trick. Thank you. All fixed.

**Comment by LefterisJP** [comment] 2021-04-28 08:52
Thanks for the confirmation @drgonzo31. The only way I can see this happening is as I mentioned above by skipping that one version that had NOK and TWD.

Anyway fixing it is easy as you saw. Changing the way things works (going from the all_assets.json to a DB) tend to be bumpy.

Closing the issue.

**Closed by LefterisJP** 2021-04-28 08:52 UTC
