### ISSUE TITLE
Swyftx

### ISSUE THREAD

**Issue by wpl123** [rotki/rotki#4450] opened 2022-06-08 01:50 UTC
## Abstract

I'm looking for a Swyftx exchange integration

## Motivation

According to some, (https://bestcryptoexchangeaustralia.com.au/) Swyftx is the best Australian based Crypto Exchange and I think it would be useful for Australian Rotki users

## Specification

The Swyftx api docs are here --> https://swyftx.docs.apiary.io/

There is a tax report endpoint and a transaction history endpoint that may be useful

**Comment by Zorlin** [comment] 2023-04-01 02:27
Strong +1 :)

**Comment by solyxius** [comment] 2024-01-21 10:16
Another +1

**Comment by damian-w** [comment] 2024-12-18 09:23
Dupe of #3211

**Comment by LefterisJP** [comment] 2024-12-18 09:28
> Dupe of #3211

Oh you are correct. Then closing this one as duplicate. Thanks for noticing

**Closed** 2024-12-18 09:29 UTC
Labels: Exchange Addition Request
