### ISSUE TITLE
Investigate why electron --type=gpu-process consumes a lot of CPU on Linux

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1701] opened 2020-11-07 00:24 UTC
## Abstract

On my Arch I realized that when I was using Rotki and the frontend was querying the backend the CPU consumption increased considerably.

After checking htop

![2020-11-07_00-18](https://user-images.githubusercontent.com/1658405/98426074-cad46600-2097-11eb-8768-5690ba7aa63e.png)

![2020-11-07_00-23](https://user-images.githubusercontent.com/1658405/98426082-cf008380-2097-11eb-91c0-dd06c57a2fbe.png)

It seems that there are 3 processes, `electron --type=renderer`, our backend and `electron --type=gpu-process`. The last one is what seems to really put a strain on the CPU.

## Task

Figure out why and address it

**Comment by kelsos** [comment] 2020-11-09 16:05
So I know for a fact that the progress animation is vuetify is heavy. And we also have issues with CSS animations on the loading screen. Testing on my machine that I know uses hardware accelaration for rendering the renderer process is at 2%. I am pretty confindent that the problem is that all the CSS animations are using a software renderer in your case so this basically degrates the performance.

My suggestion is to include a no-hardware render mode (automatically activated on electron) and selectable as a setting to the web version. This stops the animation on the login screen and also provides a simpler alternative animation for the loading bar.

**Comment by kelsos** [comment] 2020-11-26 12:06
As we discussed in the morning this is a bit more complex so I would suggest moving it to 1.10

**Comment by kelsos** [comment] 2020-12-29 14:25
I am looking if we could use the HTML5 canvas to implement the animation and how it would perform compared to css animations.

**Comment by rubenlg** [comment] 2021-09-27 20:15
FYI: I found this issue by chance. My gpu-process in Electron is also using 100% CPU when I render a square with webGL, so I suspect doing your animations with canvas instead of CSS won't help.

**Comment by kelsos** [comment] 2021-09-28 07:28
Hey @rubenlg thanks for the tip. I will keep it in mind. I think the best approach would probably be to start reducing the number of indefinite progress bars as they seem to be the biggest offenders

**Closed** 2022-02-15 13:13 UTC
Labels: frontend
