### ISSUE TITLE
Binance not syncing previous exchange transactions

### ISSUE THREAD

**Issue by maravac** [rotki/rotki#2230] opened 2021-01-31 11:22 UTC
## Problem Definition

Binance exchange transactions I made couple weeks agou are not synchronized properly. Can be the problem that all of my bitcoin balance is already moved to my hardware wallet?

## Logs

I found the rotkehlchen.log file but it is empty (also file has 0 bytes).

### System Description

Operating system: Windows 10 64bit
Rotki version: 1.13.0

**Comment by LefterisJP** [comment] 2021-01-31 11:36
Hello @maravac. Thanks for the issue!

In order to get proper logs you need to open rotki in debug mode. Here is how: https://rotki.readthedocs.io/en/latest/contribute.html#id2

Can you try to do that and check the logs?

It's most probably a cache error. Logs could help us figure out.

The way to definitely fix this is for you is to go to your settings -> Data and purge the binance exchange data and then re-request everything for binance.

**Comment by maravac** [comment] 2021-01-31 12:37
I tried to open it in a debug mode via UI as well as via manual adding the .json file, as described, but still the rotkehlchen.log file is 0 bytes (empty).

**Comment by maravac** [comment] 2021-01-31 12:44
I went to Settinds, Data, Mahade Tada, selected Exchange Binance and used the trashbin icon, then refreshed Trades and Deposit&Withdrawals, but no change, still no records from Binance anywhere.
Additionally, in Trades and Deposit&Withdrawals, I even cannot select the Binance in Filter, it's not there.

**Comment by LefterisJP** [comment] 2021-01-31 16:13
> I tried to open it in a debug mode via UI as well as via manual adding the .json file, as described, but still the rotkehlchen.log file is 0 bytes (empty).

Hello @maravac the debug mode comment concerns only the UI. Disregard the json file.

>  before log in, click the cog wheel at the bottom right corner and select “Debug” (image below). Then log in as usual.

At the log-in of the app you should be able to select the debug mode by clicking the cog wheel:

![rotki_debug_mode_set](https://user-images.githubusercontent.com/1658405/106389607-70237f80-63e4-11eb-9f06-10c14395ab18.png)

Once that is done then all further runs should keep logs. This is something that has worked for all OSes with all our users so far.

> then refreshed Trades and Deposit&Withdrawals, but no change, still no records from Binance anywhere.

So not even your old trades were fetched? Binance takes a very long time to fetch trades due to the way their API works. Are you sure the loading bar is still not running?

![2021-01-31_17-00](https://user-images.githubusercontent.com/1658405/106389930-49664880-63e6-11eb-8a2d-7041d0e15e8b.png)

I just tried to reproduce what I asked you in my local machine with 1.13.0 and it works.

**Comment by maravac** [comment] 2021-01-31 16:32
No, it just des not work. I started the Rotki application, then clicked the icon, then clicked the degug and then logged in. I refreshed trades a d Deposit&Withdrawals, waited, till "Retrieving trades for Binance" will finish. Then I opened the folde with logs (via menu Help/Logs directory), but the rotkehlchen.log file is still 0 bytes and is empty.
I think it just does not go to the debug mode.

Should I try to delete the app and its folder in \AppData\Roaming\rotki? Or should I also delete some Registry records via regedit if there are any? Or some other steps?

**Comment by maravac** [comment] 2021-01-31 17:10
Just to make it clear: at Binance I have done only very few things - all on January 5th. 2x trading the small amount of BTC directly via credit card and 1x withdrawal to my hardware wallet. Nothing else. I don't understand why Rotki does not synchronize these operations.

**Comment by LefterisJP** [comment] 2021-01-31 18:11
> No, it just des not work. I started the Rotki application, then clicked the icon, then clicked the degug and then logged in

hey @kelsos @isidorosp have you ever had a problem with windows + debug logs?

> waited, till "Retrieving trades for Binance" will finish.

Hmm wait. Perhaps I also misunderstood then. In the issue you mentioned:

> Binance exchange transactions I made couple weeks agou are not synchronized properly. Can be the problem that all of my bitcoin balance is already moved to my hardware wallet?

From that I understood that only the newest trades you got are not synchronized. But you also wrote

>Just to make it clear: at Binance I have done only very few things - all on January 5th. 2x trading the small amount of BTC directly via credit card and 1x withdrawal to my hardware wallet. 

Which leads to believe that you never got anything in either binance trades or asset movements before.

> 2x trading the small amount of BTC directly via credit card

Perhaps this kind of trade is not supported by the spot trading API. We deal with binance spot trading and I don't know if purchasing directly from credit card is supported there. Perhaps to get those we would need a different API call. I will have to do some research.

But your deposit/withdrawal if it's from their normal exchange should be shown as we use this API: https://binance-docs.github.io/apidocs/spot/en/#deposit-history-user_data

So you also went to "asset movements" and nothing appears there for binance either?

> Should I try to delete the app and its folder in \AppData\Roaming\rotki? Or should I also delete some Registry records via regedit if there are any? Or some other steps?

you can try to create a completely empty account and try again. But without the ability to have logs it's very little we can do in terms of debugging. No user either in Windows or linux, or OSX has ever reported a problem of getting debug logs so this is something we would need to solve first.

--- 

Thanks for your patience in the back and forth!

**Comment by kelsos** [comment] 2021-02-01 08:45
> > No, it just des not work. I started the Rotki application, then clicked the icon, then clicked the degug and then logged in
> 
> hey @kelsos @isidorosp have you ever had a problem with windows + debug logs?
> 

I just tried the windows binaries of v1.13.0 on Windows 10 Pro and the debug logging seems to work as expected. I enabled it through the login menu, opened the directory from the help menu and the file is there non-empty and keeps logging properly.

**Comment by isidorosp** [comment] 2021-02-01 08:51
No issue here w/ logs either (just checked and it's fine with 1.13)

**Comment by maravac** [comment] 2021-02-01 10:04
OK, I will try it on another PC Win 10 computer and will let you know.

**Comment by maravac** [comment] 2021-02-01 15:32
I tried on another PC with Win 10, but still the same - that one log file has again 0 bytes.
And btw. now it is even impossible to add the Binance exchange. When I put both API keys and try setup, it Rotki says this:

![obrazek](https://user-images.githubusercontent.com/37882327/106479862-133ecc80-64ab-11eb-8644-3b1720e801df.png)

**Comment by kelsos** [comment] 2021-02-01 15:48
Hey, @maravac it is a long shot but could you also try opening the file to verify that there is nothing there? I noticed that in the morning. The file manager size was off and lagging behind some times. The file also goes back to 0 size on every app run.

When I tried it in the morning some times it seemed that the file manager size report was lagging behind.

**Comment by LefterisJP** [comment] 2021-05-30 11:27
Insufficient information to further debug. Closing the issue.

**Closed by LefterisJP** 2021-05-30 11:27 UTC
