### ISSUE TITLE
Show liquidity pool stakes in dashboard, and count toward total net worth

### ISSUE THREAD

**Issue by hjorthjort** [rotki/rotki#1932] opened 2020-12-17 18:54 UTC
## Abstract

Include you liquidity pool stakes in total value at the top of the dashboard. Also show the stakes as a separate card in the dashboard, or simply include them in your regular balances.

## Motivation

Staked liquidity are part of your total assets. Currently it seems staked liquidity is not counted to your totals or shown in your assets. That gives a skewed balance of your actual holdings.

## Specification

The liquidity pools seem to be cached locally, at least temporarily. The interface shows the actual balances in the pools, and their value in the local currency. So it should be a matter of pulling in those balances when loading the dashboard and adding their value to the total value.

**Comment by LefterisJP** [comment] 2020-12-17 20:29
If I understand correctly this is a duplicate of: https://github.com/rotki/rotki/issues/1744

Is my understanding correct?

**Closed** 2020-12-17 22:13 UTC
