### ISSUE TITLE
Windows 10 Roti v1.9.0 crashes when trying  to add new exchange API

### ISSUE THREAD

**Issue by overanalyser** [rotki/rotki#1772] opened 2020-11-22 14:45 UTC
## Problem Definition

Trying to add a new exchange API, App shuts down as soon as + button is pressed. Starting the app again fails.

Deleting older version from the computer has not helped.

## Logs

[13896] Failed to execute script rotkehlchen-script

Traceback (most recent call last):
  File "rotkehlchen-script.py", line 2, in <module>
  File "rotkehlchen\__main__.py", line 37, in main
  File "rotkehlchen\server.py", line 54, in main
  File "rotkehlchen\api\server.py", line 269, in start
  File "site-packages\gevent\baseserver.py", line 323, in start
  File "site-packages\gevent\pywsgi.py", line 1478, in init_socket
  File "site-packages\gevent\server.py", line 180, in init_socket
  File "site-packages\gevent\server.py", line 192, in get_listener
  File "site-packages\gevent\server.py", line 288, in _tcp_listener
OSError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted: ('127.0.0.1', 4242)
Rotki API server is running at: 127.0.0.1:4242

### System Description

Operating system: Win 10
Rotki version: 1.9.0

**Comment by LefterisJP** [comment] 2020-11-22 15:42
Hey @overanalyser thanks for the report. It seems that there is two problems.

1. The crash must have not closed the backend of rotki properly in Windows. That's what the error when you start again is telling me. Can you see if there is something remaining by looking at the task manager? Then kill it and try to run rotki again. 

@kelsos  ^ This is something we need to figure out and investigate. Why did the backend in windows not shut down normally?

2. As for the original error I would need you to start rotki with the logs activated (we have them off by default so no residual data are kept unencrypted anywhere)

You do that by pressing the cog wheel at the login phase.
![2020-11-22_16-38](https://user-images.githubusercontent.com/1658405/99908164-53cade80-2ce1-11eb-9177-f1d2ef838b09.png)

@vnavascues here it would be nice if we could add the aove to the documentation ^

After doing that go to the top menu. Help -> Show logs directory. Open that folder. Then continue using rotki and try to add the exchange API key again. If it crashes again send us the contents of the log directory. It should be two log files.

**Comment by kelsos** [comment] 2020-11-23 12:12
Hey, @overanalyser I am trying to replicate this on my laptop that runs Windows 10  but so far I have no success. Is this issue happening for you only on 1.9.0?

Could you confirm if what you did before the crash was login, then got to `Accounts & Balances` and press the `+`?

Also, would it be easy for you while in the login screen to try `Help->Clear Cache` and retry again and see if the issue persists?

**Comment by LefterisJP** [comment] 2020-11-29 12:51
Hey @overanalyser we can not replicate so we will probably close without any more information.

**Comment by overanalyser** [comment] 2020-11-30 11:22
Hi Guys,

Sorry, I missed your emails.

I've just tried 1.9.0 again, with the log turned on before I logged in.

Everything works fine...

I'm not sure what has changed on my PC (other than a restarts).

Thanks

OA

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by LefterisJP** [comment] 2020-11-30 11:36
All right @overanalyser thank you for the response. I will close the issue then since we can't reproduce it. If you get any more problems let us know. Also a new release, v1.9.1 is out. It's probably a good idea to upgrade.

**Closed by LefterisJP** 2020-11-30 11:36 UTC
