### ISSUE TITLE
Failed query for Kraken: Error: EGeneral:Invalid argument when API key has a limit in the time range it can query

### ISSUE THREAD

**Issue by bengii** [rotki/rotki#1438] opened 2020-09-04 12:31 UTC
## Problem Definition

Kraken API key is accepted but when I click on trades or closed ordered I get error:
"Failed query for Kraken: Error: EGeneral:Invalid arguments"

### System Description

running latest Rotki v1.7 on up to date windows laptop, enrolled in premium Aug 31st

**Comment by LefterisJP** [comment] 2020-09-04 14:34
Hey @bengii thanks for the issue.

This is strange. Can you please join [discord](https://discord.gg/aGCxHG7) and DM me with the logs of your run where that faulure happened? Does this always happen?

Alternatively you can look at the logs yourself and you can try to see more information on the error itself and post it here. To find the location of the logs from inside the application go to Help -> Logs directory

**Comment by LefterisJP** [comment] 2020-09-04 16:17
All right so thanks to some nice back and forth with @bengii we figured this out. Apparently Kraken allows users to limit the time range that can be queried by a given API key. He was using that option.

![2020-09-04_17-32](https://user-images.githubusercontent.com/1658405/92261739-4409de00-eeda-11ea-9351-b248eddfedfd.png)

But Rotki is not aware of any such limtiations and since there is no way to even query the permissions of the API key just breaks. And the error is the `EGeneral: Invalid argument`.

There is no real solution here apart from:

(1) mentioning it in the docs for kraken which should happen when https://github.com/rotki/rotki/issues/1252 is tackled
(2) Do a different range query when trying to validate the API key. At the moment it only tries to see if the ledger endpoint is accessible with the API key but with start/end being 0.
https://github.com/rotki/rotki/blob/76d513f8570042af2e74ac3e9b934e38b435ddac/rotkehlchen/exchanges/kraken.py#L339-L342

If this change from start 0 to end being the current timestamp then we would see the `EGeneral: Invalid argument` if the user has put limits on the key. And then Rotki could warn them accordingly.

**Comment by LefterisJP** [comment] 2020-11-03 10:48
Closing this. I tried to reproduce with a new api key with range query limits and there is no longer an error if you query out of the allowed API key range. It just does not return any data which is fine. We should still add a docs entry warning the user to not set those ranges when we do #1252 

But there is no need for any extra handling on our end.

**Closed by LefterisJP** 2020-11-03 10:48 UTC
Labels: backend, good first issue, hacktoberfest
