### ISSUE TITLE
Weird blank API response using Brave/chromium browser (caching issue?)

### ISSUE THREAD

**Issue by DaWe35** [rotki/rotki#8173] opened 2024-06-26 09:27 UTC
## Problem Definition

Curl and Firefox works, but when I open `http://localhost:8084/api/1/airdrops/metadata` in Brave, I get a blank page:

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="UI of the rotki application">
    <meta name="author" content="Rotki Solutions GmbH">
    <link rel="shortcut icon" href="[./apple-touch-icon.png](http://localhost:8084/api/1/airdrops/apple-touch-icon.png)" />
    <link rel="apple-touch-icon" sizes="180x180" href="[./apple-touch-icon.png](http://localhost:8084/api/1/airdrops/apple-touch-icon.png)">
    <link rel="icon" type="image/png" sizes="32x32" href="[./favicon-32x32.png](http://localhost:8084/api/1/airdrops/favicon-32x32.png)">
    <link rel="icon" type="image/png" sizes="16x16" href="[./favicon-16x16.png](http://localhost:8084/api/1/airdrops/favicon-16x16.png)">
    <link rel="manifest" href="[./site.webmanifest](http://localhost:8084/api/1/airdrops/site.webmanifest)" crossorigin="use-credentials">
    <title>rotki</title>
  <script type="module" crossorigin src="[./index-BnD2jJSk.js](http://localhost:8084/api/1/airdrops/index-BnD2jJSk.js)"></script>
  <link rel="modulepreload" crossorigin href="[./vendor-CF5xiI-j.js](http://localhost:8084/api/1/airdrops/vendor-CF5xiI-j.js)">
  <link rel="stylesheet" crossorigin href="[./index-Cz0U3_6y.css](http://localhost:8084/api/1/airdrops/index-Cz0U3_6y.css)">
</head>

<body>
    <div id="app"></div>

</body>

</html>
```

### System Description

Operating system: Arch
Rotki version: develop 1340af5cfbe789686e5f4248ec95d4baf48b7576

**Comment by kelsos** [comment] 2024-06-26 10:47
Hey @DaWe35 can you check what the docker logs show when you call this from brave compared to when you call it from firefox/curl?

Also can you try with brave and trailing slash?

**Comment by DaWe35** [comment] 2024-06-26 12:40
Sure.
With slash, the API does not work, but I tried it anyway, same blank result in Brave.
What I noticed is that if I load the page with a hard refresh, it works. Then a normal F5 reload, and it's blank again. It might be a caching issue or something.
```
// ctrl + F5 (shows json)
172.17.0.1 - - [26/Jun/2024:12:37:43 +0000] "GET /api/1/airdrops/metadata HTTP/1.1" 200 2112 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
172.17.0.1 - - [26/Jun/2024:12:37:43 +0000] "GET /favicon.ico HTTP/1.1" 200 15406 "http://localhost:8084/api/1/airdrops/metadata" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"


// F5 (blank page)
172.17.0.1 - - [26/Jun/2024:12:38:32 +0000] "GET /api/1/airdrops/vendor-CF5xiI-j.js HTTP/1.1" 404 151 "http://localhost:8084/api/1/airdrops/metadata" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
172.17.0.1 - - [26/Jun/2024:12:38:32 +0000] "GET /api/1/airdrops/index-BnD2jJSk.js HTTP/1.1" 404 151 "http://localhost:8084/api/1/airdrops/metadata" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
172.17.0.1 - - [26/Jun/2024:12:38:32 +0000] "GET /api/1/airdrops/index-Cz0U3_6y.css HTTP/1.1" 404 151 "http://localhost:8084/api/1/airdrops/metadata" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
172.17.0.1 - - [26/Jun/2024:12:38:32 +0000] "GET /api/1/airdrops/site.webmanifest HTTP/1.1" 404 151 "http://localhost:8084/api/1/airdrops/metadata" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"

```

**Comment by DaWe35** [comment] 2024-06-26 12:41
Update: I noticed the same happening on all pages. When I open http://localhost:8084/ it's blank white, F5 does nothing. ctrl+F5 fixes.

**Comment by DaWe35** [comment] 2024-06-26 12:42
I was able to reproduce the white API bug in chromium. Now the home page works for some reason.
![image](https://github.com/rotki/rotki/assets/10603822/81a58f05-138c-4e4e-a90a-216b351f3b56)

**Comment by kelsos** [comment] 2024-06-26 17:45
Hey @DaWe35 so I had some time to check. 

First please be careful when using `develop` there is no guarantee that any created using a specific `develop` commit are going to be compatible with other commits or the next release. 

We often break the schema between commits, the only guarantee is between releases.

So back to the problem at hand, we are using service workers to track changes in the frontend when users run the app using docker so that we avoid possible incompatibilities between backend and frontend.

We have a number of users that also run the frontend from custom sub-paths instead of the route URLs. What happens is the moment you load the frontend the worker gets registered, and then when you try to open the app, the worker tries to start the application but fails, that's why you see the empty white page.

Is there something specific that you are trying to achieve? I cannot imagine anyone needing to call an API endpoint from the browser outside of limited debugging, since this would only work for a really limited subset of our endpoints.

What you can do temporarily is go to `Application` tab of the dev tools and delete the service worker. From that point and until you open the frontend again you should be able to access the api endpoints without any issue.

@lukicenturi can you maybe do a quick investigation to see if it is possible to avoid this happening when URL sub-path starts with `/api/1/`?

**Comment by DaWe35** [comment] 2024-06-26 23:03
Got it, I mean if it only bothers me, we can close this

**Comment by lukicenturi** [comment] 2024-06-28 09:29
Hi, so we need to close this because there is known issue about PWA https://github.com/vite-pwa/vite-plugin-pwa/issues/33, the issue is the `index.html` is always cached (we try to do several things, but it doesn't work). 

Also you can do this
```
What you can do temporarily is go to Application tab of the dev tools and delete the service worker. From that point and until you open the frontend again you should be able to access the api endpoints without any issue.
```
and the cache should be clear

**Closed** 2024-06-28 09:29 UTC
Labels: wontfix
