### ISSUE TITLE
FR: Improved PNL analysis for frequent trades and improve "Trades view"

### ISSUE THREAD

**Issue by magicdude4eva** [rotki/rotki#3483] opened 2021-09-19 06:58 UTC
## Abstract
I am using a crypto-bot (Gunbot) which trades about 30-60 times a day. It would be great to have an improved PNL report.

## Motivation
Better insight on portfolio performance

## Specification
I can only provide some screenshots how Gunbot does it. 

For the Trades view it would be great to have a profit/loss view on trades being sold (I am not sure if it is possible to correlate this between buys and sales) - example info:
<img width="414" alt="CleanShot 2021-09-19 at 08 56 25@2x" src="https://user-images.githubusercontent.com/1632781/133918543-0d566c0c-df13-4dc0-a4ab-009c18daca3c.png">

Idea for PNL view:
<img width="1800" alt="CleanShot 2021-09-19 at 08 57 25@2x" src="https://user-images.githubusercontent.com/1632781/133918551-768bbba3-3cf6-4606-b3b0-3a248e7b64f2.png">

<img width="1813" alt="CleanShot 2021-09-19 at 08 57 59@2x" src="https://user-images.githubusercontent.com/1632781/133918566-99e359ab-22a6-4c87-8755-edf41666c528.png">

**Comment by LefterisJP** [comment] 2021-09-19 08:04
Hey @magicdude4eva thanks for the issue!

If I understand correctly, what you are asking for is part of our PNL report. As long as rotki knows where everything was bought it will let you know how much each trade gained or lost in a FiFo way.

https://rotki.readthedocs.io/en/latest/usage_guide.html?#cost-basis

We just show this in a table and most importantly export this in a CSV. We don't currently have such pretty analytics.

It would indeed be cool to have, but since the PnL report only runs on demand and never on the background at the moment to get such stats on other views we would need to make architectural changes to run it also on the background.

A good issue to follow up on this is https://github.com/rotki/rotki/issues/701 where after running PnL on the background we plan to use the generated data in order to create overlays in various views augmenting them with more information.

**Comment by LefterisJP** [comment] 2022-05-28 08:19
Closing as duplicate of #701, since in essence it is asking for work to be done that requires 701 and describes the same cool stuff we can get after it.

We are taking the feedback and screenshots though! Thank you.

**Closed by LefterisJP** 2022-05-28 08:19 UTC
