### ISSUE TITLE
Failed at database upgrade from version 31 to 32

### ISSUE THREAD

**Issue by HydraGene** [rotki/rotki#4381] opened 2022-05-28 11:48 UTC
## Problem Definition

Login fails with following message:
`Failed at database upgrade from version 31 to 32: UNIQUE constraint failed: history_events_copy.event_identifier, history_events_copy.sequence_index`

## Logs

Which logs do you need, if you need any?

### System Description

Operating system: Debian Buster (using the AppImage)
Rotki version: 1.24.0

**Comment by LefterisJP** [comment] 2022-05-28 12:48
Hey hello @HydraGene. This is quite weird. I am not sure why this would happen but we can investigate if you can provide us with the database and the password. You can do so via a discord DM: https://discord.com/invite/aGCxHG7
(have DMs open there is a captcha challenge)

## What we need

rotki would have taken a copy of the database right before attempting the DB upgrade. So we need this. You can also revert to this and use the previous version until we figure out what's wrong.

Since you are in Linux the database is:

`~/.local/share/rotki/data/XXX` where `XXX` is your username.

The current database is `rotkehlchen.db`. Right before a DB upgrade a backup is taken so it should look like `1653690238_rotkehlchen_db_v31.backup` where the initial number is timestamp of the backup and vXX is the version of the DB at the time.

Please send me that file and the password in order to be able to debug this. Logs will not help with such an error.

## How to keep using rotki in the meantime

You can copy that backup file and rename `rotkehlchen.db`, replacing the database with the backup eventually. And then open rotki again with 1.23.4 until we figure out what's wrong.

**Comment by LefterisJP** [comment] 2022-05-28 13:19
For the devs: By looking at the code it has to be a special case of data that the function `_update_history_entries_from_kraken`
does not properly take care of. https://github.com/rotki/rotki/blob/6b85c5c53b8eb0af20c4cdb780fb3fec2c65f68f/rotkehlchen/db/upgrades/v31_v32.py#L134 

I tried to just add a duplicate sequence index and event identifier in the DB upgrade kraken data and the sequence index was changed and upgrade worked. So the only logical explanation is that there must be a case not covered by the upgrade.

**Comment by LefterisJP** [comment] 2022-05-28 14:33
Hey @HydraGene I may have found the problem and a solution.

Can you download this nightly? It's the same as v1.24.0 with only a small added fix to see if it can solve your problem at upgrade.

(Links expire 1 week from this post)
Linux appimage: https://we.tl/t-UVuC3yXvFy

Once you have the binary, make sure to have all copies of rotki closed. Then find your rotki data directory, depending on your operating system as per the [usage guide](https://rotki.readthedocs.io/en/latest/usage_guide.html#rotki-data-directory).

Under there there should be a directory with your username. For example in linux:
`~/.local/share/rotki/data/XXX` where `XXX` is your username.

The current database is rotkehlchen.db. Right before a DB upgrade a backup is taken so it should look like 1653690238_rotkehlchen_db_v31.backup where the initial number is the timestamp (won't be the same -- can be any number) of the backup and vXX is the version of the DB at the time. The number you need should be v31.

Once you have all those:

1. Copy and replace the `rotkehlchen.db` file with the v31 backup
2. Open rotki again with the nightly I gave you to test and let me know if it works.

**Comment by HydraGene** [comment] 2022-05-28 14:36
Hey @LefterisJP 
I see the comment for the devs. Looks like you already have a possible solution. Will it already be fixed without sending my DB file?
I got 1.23.4 running again and have access to my database again. Thanks.

**Comment by LefterisJP** [comment] 2022-05-28 14:38
> Hey @LefterisJP I see the comment for the devs. Looks like you already have a possible solution. Will it already be fixed without sending my DB file? I got 1.23.4 running again and have access to my database again. Thanks.

Check my comment which I must have typed at the same time as you. Perhaps we found a solution. Check it out and let me know!

**Comment by HydraGene** [comment] 2022-05-28 15:03
Great! I got in without any problem. Everything seems to work like a charm.

**Comment by LefterisJP** [comment] 2022-05-28 15:10
> Great! I got in without any problem. Everything seems to work like a charm.

Just to make sure, you can confirm that using the nightly above and upgrading from v1.23.4 worked fine?

If so yay! problem solved :)

Also if so, then you can actually even revert back to using the original 1.24.0. This nightly only had a code change that took effect during the upgrade of your database and using the normal 1.24.0 should be fine.

**Comment by HydraGene** [comment] 2022-05-28 15:32
Yes, I can confirm. 
I've downloaded the nightly linux appimage, used the 1.23.4 database, ran the nightly, and got to login with no errors.
I am using the official 1.24.0 build now, and indeed it is still working fine. 
Thanks a lot!

**Comment by LefterisJP** [comment] 2022-05-30 09:30
This is confirmed fixed by the user and will be deployed in 1.24.1

**Closed by LefterisJP** 2022-05-30 09:30 UTC
