### ISSUE TITLE
Visualize Money flow

### ISSUE THREAD

**Issue by eis2k** [rotki/rotki#4066] opened 2022-02-08 14:59 UTC
## Abstract

I must trace mined Ether that was stolen. Therefore, I ordered rotki premium, which already has some very good features to achieve this. But I was wondering if it's possible to add the GraphQL from bitquery.io to the external services. The money flow abilities are very good, but to get it all together, bitquery isn't the right place. Also, the feature to generate a sankey flow chart to visualize the money flow is fantastic. 

And last but not least, the coin path feature to identify transaction even through hundreds of hobs is more then awesome.
Imho this would be a great benefit for rotki to add this page as external service. With this rotki would do a big step for AML and fraud detection.

## Motivation

When you import the inbound and outbound money flow for every imported ether address, that would make it possible to connect the transactions over all regarding accounts to draw the flow of the money over hundreds accounts.

## Specification

just GraphQL. usual Ether tech. When importing by GraphQL, it could dramatically reduce the traffic.

**Comment by LefterisJP** [comment] 2022-02-08 15:17
Which particular query from bitquery.io are you referring to? This request sounds quite similar to https://github.com/rotki/rotki/issues/1524

**Comment by eis2k** [comment] 2022-02-08 19:05
The inflow
the outflow
and the visualization of that with the graph and the sankey visu

**Comment by eis2k** [comment] 2022-02-08 19:08
https://graphql.bitquery.io/ide/Copy-of-Coinpath-moneyflow

**Comment by eis2k** [comment] 2022-02-08 19:09
Just change the 0xxxxxx to the adress you want to analyse

**Comment by LefterisJP** [comment] 2022-02-08 19:31
I see. Unfortunately this is just heir playground. To use bitquery programatically one needs to contact them and get a paid api key plan as seen here: https://bitquery.io/forms/api

Something which can not work with rotki due to our opensource nature and inability to store api keys in the opensource app.

In any case we will try to make something similar to what you describe when we tackle #1524, so closing this as duplicate of that issue.

If bitquery ever has an open version of their api we will see if we can also integrate part of their stuff as it seems interesting.

**Closed by LefterisJP** 2022-02-08 19:31 UTC

**Comment by eis2k** [comment] 2022-02-08 19:49
yeah thats why it should be added as external servie. i have an account and its free for 1 million calls LIKE THE OTHER EXTERNAL SERVICES
