### ISSUE TITLE
General feedback on ubuntu 18.04

### ISSUE THREAD

**Issue by davbre** [rotki/rotki#1212] opened 2020-07-25 13:03 UTC
This is to note some general feedback I have from using Rotki (currently v1.6.1) on ubuntu 18.04. I tried it last year and again recently and can see there's been huge progress in that time. Good job! So, for me it's reasonably close to being an application I would use and pay for. But it's not quite working for me yet...

I've added API keys for several exchanges and I would like to produce a tax report for a particular year. I have a few problems with how this currently works:

- it takes 5-10 minutes for about 1000 trades for the relevant year. I don't know how it's working under the hood - is it freshly polling the exchanges each time a tax report is being generated? If so, could the data not be saved locally and only re-imported on request?

- I get various notifications when generating the tax report, currently these ones:
```
Periodic client query
Error at periodic client query: Error: timeout of 30000ms exceeded
Error: timeout of 30000ms exceeded
...
...
Failed to read hash as a hash during etherscan transaction query. Skipping transaction
Failed to read hash as a hash during etherscan transaction query. Skipping transaction
```
The feedback here is vague so not clear what the issue is.

- When I look at the tax report I can see the numbers are not right because I've used other software to do tax reporting for the same year. It turns out that trades from bittrex are not showing up (I figured it out using the dates). It would help if there was a column in the tax reporting table showing the exchange for each trade.

- it would be nice if tax reports could be stored in the application. Currently when the application is closed previous reporting is gone.

- the "Trades" menu is a drop-down menu but only has one item "OTC trades". This is where I would expect to view trades made on exchanges as well, and it would be great to be able to view these trades.

- On the "Accounts and Balances" page some of the amounts have asterisks after them. It's not clear to me what these mean.

- when filling out an OTC trade form and one of the required fields is missing an error message is displayed. But all previously entered data is deleted and has to be re-entered. Would be nice if previously entered data was kept in the form.

- import of trade data from bitcoin.tax would be nice (they provide an export to csv)

**Comment by LefterisJP** [comment] 2020-07-25 17:02
Hello @davbre! Very happy to hear you like the progress we have had so far. I don't know if you are following me or the team [on Twitter](https://twitter.com/LefterisJP/status/1285582101220294656) but we have also just decided to focus on Rotki 100% and quit our other jobs so that we can grow this project. It is only going to get better from here!

> So, for me it's reasonably close to being an application I would use and pay for. But it's not quite working for me yet...

Good to hear. And thank you for taking the time to sit and write some great and constructive feedback. We will address them one by one below.

If you like Rotki please consider spreading the word about it to your friends and also becoming a premium user as this is the only way for us to get enough revenue to grow the team and turn this into the best portfolio tracking and accounting tool available out there!

----

So now for your issues

### Long time for tax reporting

> it takes 5-10 minutes for about 1000 trades for the relevant year. I don't know how it's working under the hood - is it freshly polling the exchanges each time a tax report is being generated? If so, could the data not be saved locally and only re-imported on request?

Under the hood, the first time a particular exchange query is done for a time range it will take longer. After that we should be caching everything in the database for that range. Also historical prices for each asset encountered are queried from cryptocompare and that also takes quite a long time ... but once finished it's all cached locally and should no longer take a long time.

The problem is that even if only 1 more day passes and you include that in the time range then all exchanges need to be queried again.

May I ask which exchanges are included in the query? Binance for example is terrible as it offers no way to query all the user trades but you to do an API query per market pair. And that takes a long time since Binance has a lot of pairs.

We have an issue for that: https://github.com/rotki/rotki/issues/1073 but not sure what approach we can take as it's a limitation of the binance API.

Also a related issue we should work on is to maintain backend querying tasks before the user goes to tax reporting: https://github.com/rotki/rotki/issues/968

This will greatly relieve the pressure on the tax reporting task and should speed things up considerably.

### Errors/notifications at tax reporting

> I get various notifications when generating the tax report, currently these ones:

Okay these look like problems/bugs. Can you share with me (privately is better) the rotkehlchen.log of a tax report run? This way I can probably try to figure out what is wrong.

### Bittrex trades missing

>  It turns out that trades from bittrex are not showing up (I figured it out using the dates). 

Missing trades from a supported exchange would definitely be a bug. Can you share the rotkehlchen.log of a tax report run, so that we can investigate? As I said above privately is better. Either via email to lefteris [at] rotki [dot] com or at our [discord](https://discord.gg/aGCxHG7 ) or [Telegram](https://t.me/rotkichat).

> It would help if there was a column in the tax reporting table showing the exchange for each trade.

That's interesting. I thought the location was part of each row. If it's not we should fix that. I will make an issue.

### Storing tax reports

> it would be nice if tax reports could be stored in the application. Currently when the application is closed previous reporting is gone.

In theory if the range is the same re-creating the tax report should be fast as almost everything should be saved in the DB. But perhaps also storing the report itself somewhere would make sense. For ease of development such stored reports would not be maintained compatible between rotki versions if anything. Perhaps will make an issue to discuss this on its own right.

### Trades Menu

> the "Trades" menu is a drop-down menu but only has one item "OTC trades". This is where I would expect to view trades made on exchanges as well, and it would be great to be able to view these trades.

Absolutely. We want to offer this. And there is an issue for that: https://github.com/rotki/rotki/issues/1085

### Asterisks on amount

> On the "Accounts and Balances" page some of the amounts have asterisks after them. It's not clear to me what these mean.

The asterisks mean that the particular amount has been rounded up. The rounding is specified by your user settings where you specify the number of floating point decimals numbers should be rounded up to.

By hovering on top of the asterisk you should be able to see a tooltip with the actual amount before the rounding.

We expect users to hover over the asterisk and since they see the non-rounded amount to understand what the `*` means. But perhaps that is not the best UX strategy. Do you have any suggestions to improve this?

Also pinging @isidorosp and @kelsos here since we all thought this would have been straighforward for users to understand.


### Keep OTC trade data in the form in case of error

> when filling out an OTC trade form and one of the required fields is missing an error message is displayed. But all previously entered data is deleted and has to be re-entered. Would be nice if previously entered data was kept in the form.

Absolutely. I will make an issue for it.

### Bitcoin.tax import

> import of trade data from bitcoin.tax would be nice (they provide an export to csv)

You are the second person to ask for this so perhaps it's not a bad idea. There are two issues with this:

1. Generally importing data from other services via CSV is hard since the other services seem to change their export format often. This has caused us a lot of headaches with the cointracking.info imports.
2. If the data format is incomplete and missing required data then we have to extrapolate data and that is always bad for the user and would be worse than simply importing your data directly from an exchange with an API key or from the blockchain.

Still we can make an issue for this and discuss it there.


---

We will keep this issue open for the feedback and link other issues for action items for each feedback entry you provided. At some point if/when everything has its own issue/thread we will close this.

Until then feel free to add more feedback here or even make more issues.

Thank you for using Rotki!

**Comment by LefterisJP** [comment] 2020-11-22 22:22
Since we have issues for all of the feedback in here I think it's safe to close it. Again thank you so much for your feedback and your support. Feel free to open new issues with stuff you would like to see.

**Closed by LefterisJP** 2020-11-22 22:22 UTC
Labels: Feedback
