### ISSUE TITLE
Task for Derive new xpub addresses died with exception: Blockchain account/s ['bc123', 'bc145'] already exist

### ISSUE THREAD

**Issue by kilrau** [rotki/rotki#1695] opened 2020-11-05 12:58 UTC
## Problem Definition
Minor bug which causes a notification but no real consequences:
`Task for Derive new xpub addresses died with exception: Blockchain account/s ['bc123', 'bc145'] already exist. Check the logs for more details`

## Logs
Can add if needed.

### System Description
Operating system: ubuntu 20.04
Rotki version: 1.8.3

**Comment by LefterisJP** [comment] 2020-11-05 13:05
Hey @kilrau interesting. I would actually like the logs for this. Can you pm them to me in discord?

**Comment by LefterisJP** [comment] 2020-11-06 18:47
After looking at this I think it's similar to what you have also reported in discord and the reason I made the bitcoin xpub lock issue: https://github.com/rotki/rotki/issues/1658

With the lock in place this should not happen. This error is just a single manifestation of the race condition that can occur without a lock.

**Comment by kilrau** [comment] 2020-11-06 19:32
Thx, but https://github.com/rotki/rotki/pull/1683 was merged 3 days ago and I got this with the nightly from yesterday. I can test again with a nightly where you can be sure the lock is in - just point me at it.

**Comment by LefterisJP** [comment] 2020-11-06 22:25
Aha, I did not know it was with the nightly from yesterday. I thought this was with 1.8.3

Let's take it via discord PM.

**Comment by kilrau** [comment] 2020-11-21 10:25
Just got this one with `1.9.0`, please reopen @LefterisJP

**Comment by LefterisJP** [comment] 2020-11-21 10:27
yes I also did. Will reopen. But it's a non fatal error. It's just a warning.

**Comment by kilrau** [comment] 2020-11-30 09:04
I didn't get this notification anymore in the last weeks with `1.9.0` nor today with `1.9.1`, but my xpub is still missing addresses, so would you guys want to treat this issue as "missing addresses" since it's somewhat possible the failure to continue deriving is caused by this OR close and open a new issue?

**Comment by LefterisJP** [comment] 2020-11-30 09:46
The missing addresses issue is here: https://github.com/rotki/rotki/issues/1759

Let's see about this issue. I would have to check if it is indeed fixed. I had seen it in the past too and can't recall doing something extra after the last time I saw it to fix it. So logically it may still be there.

Should not be related to missing xpubs.

**Comment by LefterisJP** [comment] 2020-12-22 10:25
@kilrau I can't reproduce this issue anymore either. I am going to close it. The missing addresses issue is another one and I am still not sure how to fix.

**Closed by LefterisJP** 2020-12-22 10:25 UTC
Labels: bug, investigating

**Comment by kilrau** [comment] 2020-12-22 10:43
> I can't reproduce this issue anymore either. I am going to close it.

Ok, I haven't seen it in a while neither.

> The missing addresses issue is another one and I am still not sure how to fix.

Yeah, this one is a biggie though. Missing to catch quite some coins :/ Did the wasabi test wallet we created help in anyway?

**Comment by LefterisJP** [comment] 2020-12-22 10:46
> Yeah, this one is a biggie though. Missing to catch quite some coins :/ Did the wasabi test wallet we created help in anyway?

No at least in my case all addresses are shown properly.
