### ISSUE TITLE
Timeout when creating task reports

### ISSUE THREAD

**Issue by TimDaub** [rotki/rotki#1314] opened 2020-08-11 12:24 UTC
## Problem Definition

When generating a tax report for the year 2019, I now often get the following error:

<img width="372" alt="Screen Shot 2020-08-11 at 14 22 28" src="https://user-images.githubusercontent.com/2758453/89896708-34022580-dbde-11ea-83bc-4dbe27178d37.png">

I've checked the logs in rotkehlchen.log, but I wasn't able to find the exact error messages in the file...
Usually, the second time I start creating the report, it works. This issue is still somewhat annoying.

### System Description

My latest commit: f399fe9fafcad0407c8782c0b538183a05396f4a

**Comment by LefterisJP** [comment] 2020-08-11 12:41
Hmmm this is a very unusual error. From the errors you pasted it seems as if there was a timeout somewhere and then the tax report task was dropped.

I have just created a tax report on develop with a lot of data and have not seen such an error. So it probably depends on your data. Something in the way rotki queries your data times out somewhere and the task report task is dropped. We have to find out what that something is. The only way to do this is look at the logs.

From your description, I have a suspicion it may be the way we query cryptocompare historical prices for all times during the tax report. After the query is done the price history data are cached locally. So would make sense that the second time it works okay. And perhaps there is so much action during that query and no context switching whatsoever happens which would lead to this.

This happens only when a greenlet (a thread) is not context switching and is so busy working that it does not yield to other threads ever. So everything else is starved. In this case the periodic task query.

I can do an experiment here to verify this hypothesis by deleting all my historical price caches.

**Comment by LefterisJP** [comment] 2020-08-11 16:11
> I can do an experiment here to verify this hypothesis by deleting all my historical price caches.

I did that experiment ... but did not get the timeout. It took A LOT of time with my data but finished just fine.

The only thing I got was heavy rate limiting from cryptocompare due to the sheer amount of historical queries after having completely deleted the cache. Due to that we had some errros:

```
Skipping action at 27/07/2020, 16:53:59 during history processing due to inability to reach an external service at that point in time: Failed to query cryptocompare for: "https://min-api.cryptocompare.com/data/v2/histohour?fsym=LEND&tsym=EUR&limit=2000&toTs=1445587200". Error: You are over your rate limit please upgrade your account!. Check the logs for more details
```

Got 9 errors like that which were not there when I ran the tax report again. To counter against them we can only:
1. Ask user to get a cryptocompare API key with higher limits
2. Utilize additional price data feed like coingecko: https://github.com/rotki/rotki/issues/224
3. Maintain multiple backend tasks querying information beforehand so that when the user clicks the tax report not everything is queried at once (https://github.com/rotki/rotki/issues/968)

---

Anyway this does not solve your issue though. I wonder how to reproduce. The only way I can think of is to see your entire log and hope it's properly logged there. Or mimic your setup by getting API keys + data from you. Both of which are far from ideal for your own privacy.

**Comment by TimDaub** [comment] 2020-08-11 16:15
Thanks for your thorough investigation.
Unfortunately, I'm not able to reproduce the error anymore since [I've cleared out my cache](https://github.com/rotki/rotki/issues/1302#issuecomment-671927866). I imagine it had to do with outdated data. For me, the problem is solved.

**Comment by LefterisJP** [comment] 2020-08-11 18:39
All right thanks that's nice, so closing for now.

 If anyone else sees this we can reopen another issue and add data that would help us figure out what's happening.

**Closed by LefterisJP** 2020-08-11 18:39 UTC
