### ISSUE TITLE
Add option to opt out from auto-detecting/adding layer2s like Polygon to avoid spam tokens appearing in portfolio

### ISSUE THREAD

**Issue by kilrau** [rotki/rotki#6885] opened 2023-11-03 10:52 UTC
## Abstract

I'd like to opt out from this
![image](https://github.com/rotki/rotki/assets/19181985/0197f2ca-9240-49e0-bd1c-25b3e6276fdd)
to prevent this
![image](https://github.com/rotki/rotki/assets/19181985/80c46e2f-3c17-48ef-96b6-b053e6bf64df)

## Motivation

Quite tedious to go to `Accounts & Balances` -> `Polygon POS BALANCES` -> Select all -> Delete every time I'm opening rotki. Also I would claim in general the behavior to auto-add Polygon is rather questionable since I've never used Polygon with my addresses in rotki before.

## Specification

`v1.30.2`

**Comment by LefterisJP** [comment] 2023-11-03 11:09
Hey @kilrau this is a valid request. Polygon is unfortunately a source of spam and many users use it so the problem is figuring ourt spam versus real events.

It's an ever continuing battle. Please hop on to our discord if you wanna chat more about it: https://discord.rotki.com/

But yeah opting out of certain EVM chains completely is a good ask.

**Comment by kilrau** [comment] 2023-11-03 11:18
Joined your discord.

> opting out of certain EVM chains completely is a good ask.

That's basically it. I know which chains I'm interested in in which not :)

**Comment by kilrau** [comment] 2023-12-04 10:33
Can you consider changing default to opt-in instead of opt-out? I think you should be able to use the merged backend PR as-is just let the frontend opt-out from all by default. Today Gnosis was suddenly added and I don't want to spend time opting out from newly added chains forever.

In future considering scanning chains in the background and only auto-add if >0 value was detected.

**Comment by yabirgb** [comment] 2023-12-11 08:54
Closing the issue as completed in https://github.com/rotki/rotki/pull/7016

**Closed by yabirgb** 2023-12-11 08:54 UTC
