### ISSUE TITLE
Profit & Loss time greyed out if after current time, no matter the date

### ISSUE THREAD

**Issue by drgonzo31** [rotki/rotki#3224] opened 2021-07-18 07:38 UTC
## Problem Definition
When generating a P&L report. Selecting a time that is later than the current computer time is greyed out. This makes sense if the end date is today but not for days already passed.

### System Description
Ubuntu 21.04

Operating system: 
Rotki version: 1.19

**Comment by LefterisJP** [comment] 2021-07-18 08:15
Hey @drgonzo31!

Thanks for the issue. I am not sure I understand. You can't have a report with an end date in the future. Is that what you are asking for?

**Comment by drgonzo31** [comment] 2021-07-18 09:02
Hey @LefterisJP,
Sorry I'll try to explain better. For example,
If I want to create a P&L for the period of 1st January 2021 9am to the 1st June 2021 9am . After selection the dates. When entering the end time with the wheel. I can't select past my computer's current time. If today my time is 8am everything above 8am will be greyed out.

**Comment by LefterisJP** [comment] 2021-07-18 14:29
Yes so I understood correctly. This is a correct behaviour. Your computer's current time is "now". You can't select an end date in the future.

Unless your computer's time is misconfigured, but then this is a problem of your system.

**Comment by drgonzo31** [comment] 2021-07-18 18:36
Can you explain why I shouldn't be able to use 11:59pm for the 1st of June 2021 for the end date. If now is the 1st July 2021 8am?

**Comment by LefterisJP** [comment] 2021-07-18 18:44
Ah I see. What you mean. I can reproduce the problem.

As a workaround, you can actually type the time you want. But yes, this seems like a frontend bug.

@kelsos I am assigning it to you. The clock UI component can't go past the current time, no matter the date (even if it's not today).

As per the screenshot.
![2021-07-18_20-43](https://user-images.githubusercontent.com/1658405/126078734-ef5e960a-5e63-432c-82b9-b694d264c6a2.png)

**Comment by kelsos** [comment] 2021-07-19 07:49
Let me have a look, looks like a simple enough bug

**Comment by LefterisJP** [comment] 2021-07-19 12:44
Fixed by https://github.com/rotki/rotki/pull/3228. Will be in 1.19.1

**Closed by LefterisJP** 2021-07-19 12:44 UTC
Labels: bug, frontend
