### ISSUE TITLE
ETH2 Staking Total keeps doubling when toggling between Validator and Depositor 

### ISSUE THREAD

**Issue by dcato98** [rotki/rotki#4147] opened 2022-03-24 16:00 UTC
## Problem Definition

Note the absurdly high validator totals in the screenshots below. This was achieved by navigating to this screen and repeatedly clicking between Validator and Depositor. Each toggle results in a doubling of the previously reported total. Clicking the refresh icon resets the staking details to the appropriate values. All other information on the page appears to be correct (addresses, daily stats, events).

Happy to provide more info as needed.

### System Description
![Screenshot from 2022-03-24 11-47-49](https://user-images.githubusercontent.com/2524133/159957431-4733df5e-5159-4de1-bfd3-203b82909a9a.png)
![Screenshot from 2022-03-24 11-47-55](https://user-images.githubusercontent.com/2524133/159957439-ca7a6373-0743-4a36-aef8-513e0caed262.png)

Operating system: Pop!_OS (Ubuntu variant)
App Version: 1.23.4
Frontend Version: 1.23.4
Platform: linux x64 5.16.11-76051611-generic
Electron: 16.0.1

**Comment by yabirgb** [comment] 2022-03-24 16:29
Hello @dcato98 ! I've been trying to reproduce the error but I still get the correct value by clicking between validator and depositor. Could you give us more details of how you added the validator (validator index only, public key or both) and if you did something else that could affect this? Has this happened the first time you added the validator before closing session?

Any information that could help us to find the issue would be great :)

**Comment by LefterisJP** [comment] 2022-05-28 08:12
Closing due to lack of information and ability to reproduce

**Closed by LefterisJP** 2022-05-28 08:12 UTC
Labels: bug
