### ISSUE TITLE
BTC xPub support needs more tlc

### ISSUE THREAD

**Issue by JezSan** [rotki/rotki#1600] opened 2020-10-16 17:13 UTC
## Problem Definition

I have some regular bitcoins (legacy) and I have some new bitcoins (segwit).  They are two different xpubs.

I have entered both xpubs in for both of them, and it complains when I try to enter the second xpub, that its already been entered (when its different)

presumably the derivation paths are different

so, either it only accepts one xpub and doesnt like me entering a 2nd one?  or, perhaps it doesnt like the new segwit xpubs?  or perhaps we need another prompt to allow us to enter the derivation path as well as the xpub.

**Comment by LefterisJP** [comment] 2020-10-16 17:20
Hey @JezSan good evening! Thanks for using Rotki and for making an issue!

 As per the [release notes](https://github.com/rotki/rotki/releases/tag/v1.8.1) of v1.8.1 we only allow P2PKH (aka legacy) xpubs right now. This is why you see this behavior.

Supporting the other 2 types (segwit and native segwit) is a high priority and is scheduled for v1.8.2: https://github.com/rotki/rotki/issues/1562

Does this satisfy your problem? If yes I will close this issue as duplicate of #1562

**Comment by JezSan** [comment] 2020-10-16 17:24
Thats great news.  Please close it

**Closed** 2020-10-16 17:26 UTC
