### ISSUE TITLE
Some coinbase balances are missing

### ISSUE THREAD

**Issue by bitboy99** [rotki/rotki#2656] opened 2021-03-28 20:51 UTC
## Problem Definition

I have some Link and BTC on my coinbase account but rotki isn't reporting them although access to Link and BTC balances are checked on the API setting.

I didn't had this before, it has happened during the week.
I've tried to set some new API key but the problem is still here.

## Logs

No specific logs

### System Description

Operating system: Mac OS Catalina 10.15.7 
Rotki version: 15.2

**Comment by LefterisJP** [comment] 2021-03-28 23:16
Hello @bitboy99 thanks for the issue and thanks for using rotki!

Let's try to figure this out.

When you say, some coinbase balances, I assume then that some are displayed? Also from what you wrote I understand that all your coinbase balances were displaying properly before but now some of them are not?

Those that are not must have something in common together. Did you by any chance move them to a specific part of coinbase? A different type of wallet perhaps? Or did you just recently deposit them and have not restarted rotki or refreshed balances?

**Comment by bitboy99** [comment] 2021-03-29 05:42
Hello @LefterisJP thanks for your quick answer.

Your understanding is good, my BTC and Link balances aren't displayed by Rotki even after refreshing the balances (by clicking on the circle arrow near "exchange balances"). 

Also, my Link and BTC trades appear in the history provided by rotki. 
I haven't done anything on Coinbase concerning those assets and they are here since more than two months.
Finally, I have some Link and BTC on other exchanges supported by Rotki and their balance appear on my Rotki balance (they are displayed). 

This issue wasn't here before V.1.15.1 I guess, before (from February 21) I was using V1.14.1 and even when I go back to this version the issue is still here. I cannot go back to an older version (V1.13.1, Rotki doesn't allow me to install it).

**Comment by LefterisJP** [comment] 2021-03-30 08:55
So @bitboy99 let me understand. The issue persists no matter what rotki version you are in, right?

It sounds to me like a problem with coinbase's API and not rotki as we have really not changed anything at all in coinbase's implementation for many months. And if you are going back to a version that used to work for you (v1.14.1) and it still happens that all seems to point at a change in what coinbase itself returns via its API.

To help you further we would need:

1. Debug logs. Even though I don't think they will show anything since this is about missing balances and not an error. To see how to activate debug logs check [here](https://rotki.readthedocs.io/en/latest/contribute.html#id2).
2. A read only version of your coinbase api key to try and debug this at its source.

You should provide those in private and not here in the issue. We can chat about it in DMs in discord: https://discord.gg/aGCxHG7 or you can email us at support@rotki.com. Discord is preferred.

**Comment by coinyon** [comment] 2021-04-06 09:59
I have the same error and added a logfile here: https://github.com/rotki/rotki/issues/2678

**Comment by LefterisJP** [comment] 2021-04-06 10:09
Nothing has changed in rotki at that part of the code. And if coinbase returned the balances of those assets before,  and now suddenly it simply does not include them in the response of the "accounts" api call then I think you should open a support request with them.

Perhaps they moved them to another endpoint, or the api key needs some extra permissions. Nothing I can see with a quick look in their docs: https://developers.coinbase.com/api/v2#list-accounts

**Comment by coinyon** [comment] 2021-04-06 10:09
This also leads to the fact that the trades of those missing accounts/balances are not imported

**Comment by coinyon** [comment] 2021-04-06 10:10
@LefterisJP yea looks like it. however what is striking is that the first call returns 24 accounts and the second 25. Thats weird.

**Comment by LefterisJP** [comment] 2021-04-06 10:13
I see the second call has a pagination identifier. Perhaps it's also an error in the way we do pagination, that started showing only recently due to something.

**Comment by coinyon** [comment] 2021-04-06 10:14
Yea, I found the error, its the `not pagination_next_url` that is wrong

**Comment by coinyon** [comment] 2021-04-06 10:14
So it will only paginate once, not multiple times

**Comment by LefterisJP** [comment] 2021-04-06 10:23
Hmm isn't it paginating with recursive calls to the function below? I don't have data to confirm the problem and fix it. Can you make a PR and test it with your account? Or alternatively give me an api key to test myself and tell me what balances you expect to see.

**Comment by coinyon** [comment] 2021-04-06 10:28
Sorry too busy for an PR :-)

If I remove `not pagination_next_url` in https://github.com/rotki/rotki/blob/develop/rotkehlchen/exchanges/coinbase.py#L353, balances and trades work again for me.

**Comment by LefterisJP** [comment] 2021-04-06 10:49
I made a PR with that change. I think I can see the problem. The intention of the author was to get into the pagination **only** at the first call that needs it, and then I guess gather the results with a for loop.

But ... there is no for loop, and data are gathered via recursive calls, so that condition there must have indeed stopped querying after the first paginated call. So two queries per api query only. So if you had more, then the results would be missing.

I have almost nothing in my test coinbase account so this did not manifest. If you can confirm it works fine for you and both trades and balances show fine now, then we can consider this fixed with the PR.

**Comment by coinyon** [comment] 2021-04-06 11:28
I can confirm that the PR works for me

**Closed** 2021-04-06 11:36 UTC
