### ISSUE TITLE
Errors retrieving KuCoin trades

### ISSUE THREAD

**Issue by bgibbsjr** [rotki/rotki#2398] opened 2021-02-17 22:57 UTC
## Problem Definition

Received the following errors, when trades were being retrieved from the KuCoin exchange:

"Backend messages"
`Query history of kucoin exchange died with exception: Expected either FVal or int.. Check the logs for more details`

"Trades for KuCoin"
`Failed query for KuCoin: Error: The backend query task died unexpectedly: Expected either FVal or int.`

![image](https://user-images.githubusercontent.com/1310982/108278782-83a34a00-7149-11eb-85d3-9ec9e893486b.png)

Steps:

1. Added KuCoin exchange.
2. Switched to dashboard and saw KuCoin balances.
3. Clicked History -> Trades and the process began to retrieve the trades.
4. The "Backend messages" error appeared in the Notifications, after about a minute.
5. The "Trades for KuCoin" error appeared, after a couple of minutes.
6. Closed the application and restarted it, with Debug logging.
7. Clicked History -> Trades again and received the same errors. 

## Logs

Log files attached (but deleted from lefteris)

1. rotkehlchen.log
2. rotki_electron.log

### System Description

Operating system: Windows 10 64-bit
Rotki version: 1.14.0

**Comment by LefterisJP** [comment] 2021-02-17 23:04
Hey @bgibbsjr thanksa lot for the report. I am deleting the logs from the issue as they may contain sensitive info.

I can see where the problem is from the logs.

For some reason Kucoin for your account sends some data differently than we expect and does not agree with their api docs. Will analyze the problem and figure out a solution. It will be included in the next patch release.

**Comment by bgibbsjr** [comment] 2021-02-18 02:22
Thank-you!

**Closed** 2021-02-19 11:12 UTC
Labels: bug
