### ISSUE TITLE
Crypto CSV from CDC fails to import

### ISSUE THREAD

**Issue by Blackswan122** [rotki/rotki#3056] opened 2021-06-06 15:02 UTC
Hi,
I tried to import import the CDC file ...Crypto.. it failed.

The other two Fiat and Cards worked fine.

![CDC Rotki 3](https://user-images.githubusercontent.com/59722401/120929279-bc5f3300-c6e8-11eb-91b0-1c0d073064c1.PNG)

![CDC Rotki 2](https://user-images.githubusercontent.com/59722401/120929157-37741980-c6e8-11eb-9c2a-87c80ca7715c.PNG)
![CDC Rotki](https://user-images.githubusercontent.com/59722401/120929158-380cb000-c6e8-11eb-97a2-f3fddbfeaa5e.PNG)

I tried to send Excel CSV but it says this file not supported.

App Version: 1.17.2
Frontend Version: 1.17.2
Platform: win32 x64 10.0.19042
Electron: 12.0.7

Operating system: 
Rotki version:

**Comment by yabirgb** [comment] 2021-06-06 15:37
In order:
- First warning might be because you have an empty line in the CSV files
- About `viban_*` I don't see any code in our side to handle this kind of transactions so we need to add support for it. It would be necessary that you provided us with faked data for this type of rows.

About that error I tried with the CSV in the screenshot and is not the cause. Could you also give me fake data to check what could it be?

**Comment by Blackswan122** [comment] 2021-06-06 16:30
I tried to give you real data but the file wouldn’t send. What do you mean via fake data? 

I tried to send a real CSV with the current headers as they are and only two rows of real data the rest I deleted. 

I don’t even know what viban_* is

**Comment by yabirgb** [comment] 2021-06-06 16:35
Sorry, with fake data I meant a CSV file that didn't contain information about you (values) but is similar to what you see.
In this case headers are not the problem but some row, that is why you see `missing entry for 'debited'`.

With the `viban_` I was referring to the warnings that you see in the UI. They mention `viban_deposit`, `viban_purchase`, `viban_card_top_up`. Those are actions that we don't have any information about as we haven't seen them before.

**Comment by Blackswan122** [comment] 2021-06-06 17:52
But if it won’t accept a CSV formatted file how am I supposed to send it? Fake or real… it keeps saying file format not accepted.

**Comment by yabirgb** [comment] 2021-06-06 18:05
Sorry @Blackswan122 I believe I didn't explain well. I meant to say that if you could send either to me in discord or here the csv file that is failing so I can check why this error is showing with random numbers so no information about you is revealed.

**Comment by LefterisJP** [comment] 2021-06-06 18:41
@Blackswan122 CSV formats are experimental because crypto.com, nexo and all other CSV services changes them every other day. If you want us to fix this you will need to send us an example CSV file. You are also in discord, you can DM yabir.

@yabirgb This is why I keep saying that CSV support is hard. There is no spec. They just change it all the time. We will need to implement a generic CSV import so users can fix these stuff on their own: https://github.com/rotki/rotki/issues/2270

**Comment by LefterisJP** [comment] 2021-07-25 13:06
Any updates here? With absence of more information I am going to close the issue.

**Comment by yabirgb** [comment] 2021-07-25 14:51
Shame on me. Not for the moment. Now that I have more time I'll take a look at it ASAP. We fixed an issue related to nexo already but there are still one file failing

**Comment by LefterisJP** [comment] 2021-07-25 21:11
Yes but do you have the CSV that lead to the failure? Without it you can't debug this.

**Comment by LefterisJP** [comment] 2021-09-09 21:56
Fixed by https://github.com/rotki/rotki/pull/3424

**Closed by LefterisJP** 2021-09-09 21:56 UTC
Labels: file import
