### ISSUE TITLE
Running v1.17.2 docker image breaks blockchain balance query under some conditions

### ISSUE THREAD

**Issue by y2kboy23** [rotki/rotki#3053] opened 2021-06-04 18:43 UTC
## Problem Definition

When upgrading from 1.16.2 to any of the 1.17.x versions of the Rotki docker image, I'm seeing the following error message in my notification panel "Failed to query [object Object] balances: {"location": ["Failed to deserialize Location value [object Object]"]}". 

## Logs

Looking through the rotki.log file, I'm showing the following line item which might be the problem:

[04/06/2021 18:30:48 UTC] INFO rotkehlchen.api.server.pywsgi: 127.0.0.1 - - "GET /api/1/exchanges/balances/[object%20Object]?async_query=true HTTP/1.0" 400 295 0.002637
[04/06/2021 18:30:48 UTC] DEBUG rotkehlchen.api.rest: Request successful response={"result": null, "message": "The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again."}, status_code=404

### System Description

Operating system: Ubuntu 18.04 w/ Docker 
Rotki version: 1.17.0 - 1.17.2

**Comment by LefterisJP** [comment] 2021-06-04 18:47
hey @y2kboy23 this seems very strange. Which exchange is this that failed?

Funny that the log appears like this. I will have to look it up. The easiest way for us to debug this would be if you join discord (https://discord.gg/aGCxHG7) and send me a database that this happens with. I have never seen the logs appear like that in the DB so something may be botched with the way the upgrade happened.

**Comment by y2kboy23** [comment] 2021-06-04 18:51
It actually happened with two different exchanges, I removed one and kept Bittrex around.  I'll join the discord to troubleshoot further.

**Comment by LefterisJP** [comment] 2021-06-04 20:43
So I spent some time debugging this with @y2kboy23 via discord DMs.

This is weird.

Turns out that the DB is upgraded but the backend/frontend of the docker image is of an old rotki version even though he has upgraded to latest and we confirmed the hashes match for the docker image.

Taking the same DB and putting it in his windows machine using the windows electron app works fine.

Not really sure how this can happen. I moved my own DB to a clean rotki docker image and it worked fine.

@kelsos Can you chime in when you find time?

**Comment by yabirgb** [comment] 2021-06-04 20:52
Did he shutdown + removed the old image before downloading the new one? It may be happening that he is still using the old container.

https://rotki.readthedocs.io/en/latest/installation_guide.html#updating-to-a-newer-version

In our guide the `rm` step

**Comment by y2kboy23** [comment] 2021-06-04 21:20
Well...my browser seemed to cache the old 1.16x web resouces which conflicted with 1.17x.  All's working fine after forcing a reload of the web resources.  Thanks for all the assistance.

**Comment by yabirgb** [comment] 2021-06-04 21:28
Happy to read this! I haven't experienced this cache issue but was one of the things that came to my mind. If you need anything else let us know creating a issue or in discord. Closing this as seems to be solved.

**Closed by yabirgb** 2021-06-04 21:28 UTC

**Comment by kelsos** [comment] 2021-06-07 08:28
I opened this #3058 to provide a solution for this.
In the docker, in the lower corner of the login screen, there should be an icon to access the about screen btw.
