### ISSUE TITLE
Rotki does not use system time zone in the statistics premium component

### ISSUE THREAD

**Issue by monomachos** [rotki/rotki#1104] opened 2020-06-23 17:58 UTC
Rotki seems to translate UTC to a time zone several hours ahead of me. This can be seen when adjusting the start or end dates in the statistics page. The time zone happens to match the country where my Rotki account is registered which may offer an explanation. Nevertheless, I am residing in another country at the moment and Rotki should account for that by reading my system local time.

**Comment by isidorosp** [comment] 2020-06-23 18:16
Hi monomachos. Could please provide a little more information to help us locate the issue?

For example, what date do you see when you click on the "save status" icon in the app-bar?
![image](https://user-images.githubusercontent.com/27592/85439328-2a205680-b58d-11ea-97a6-ad74d617021b.png)

For me this date is in the timezone matching my system date. In your case does this date appear in the incorrect timezone as well?

**Comment by monomachos** [comment] 2020-06-23 18:29
Hi, that menu does detect my TZ correctly. However, upon opening the date selection menu, the current date appears as 6pm which not does not correspond with my local time.
![pic-selected-200623-1126-54](https://user-images.githubusercontent.com/59909838/85441944-7dba8200-b544-11ea-87de-b183f9d825f4.png)

**Comment by isidorosp** [comment] 2020-06-23 18:32
OK I can confirm this on my side as well, it seems to be in the premium stats component (it's using UTC).
![image](https://user-images.githubusercontent.com/27592/85442608-a9fbf000-b590-11ea-88f0-3c5239d51a32.png)

**Comment by LefterisJP** [comment] 2020-06-23 18:39
Okay so we can deploy a fix for this even without releasing a new version for the entire app. Thanks for the heads up @monomachos.

@kelsos can you help detecting what's wrong here?

**Comment by kelsos** [comment] 2020-06-23 18:54
I can have a look yes

**Comment by LefterisJP** [comment] 2020-06-23 20:33
@monomachos This should be fixed right now. And you can probably confirm it immediately since the premium components are pulled from our server since it's a paid part of the application.

If you confirm it's okay on your side we can close the issue.

Also in discord you mentioned there was another problem. If you can make an issue to describe it so that we can solve it that would be really great.

Thank you for using rotki!

**Comment by monomachos** [comment] 2020-06-23 20:36
I can confirm its working now. And thanks for the swift work. I will be reporting more bugs soon hopefully.

**Closed** 2020-06-23 21:50 UTC
