### ISSUE TITLE
Detect crypto deposits/withdrawals for Bitpanda

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#3804] opened 2021-12-08 20:19 UTC
## Abstract

A user reported that they are missing crypto deposits/withdrawals in rotki v1.22.2 and bitpanda. It seems they are right. We don't query those as they are on a different endpoint

## Task

Implement it. The endpoint should be this one: https://developers.bitpanda.com/platform/#/transactions-get

The user was kind enough to send example response.

```json
{
    "data": [
        {
            "type": "wallet_transaction",
            "attributes": {
                "amount": "6608.34105600",
                "recipient": "0xanaddress",
                "time": {
                    "date_iso8601": "2021-10-10T09:01:12+02:00",
                    "unix": "1633849272"
                },
                "confirmations": 56,
                "in_or_out": "incoming",
                "type": "deposit",
                "status": "finished",
                "amount_eur": "5718.43",
                "amount_eur_incl_fee": "5718.43",
                "wallet_id": "XXX",
                "confirmation_by": "not_required",
                "confirmed": false,
                "cryptocoin_id": "27",
                "cryptocoin_symbol": "USDT",
                "last_changed": {
                    "date_iso8601": "2021-10-10T09:15:45+02:00",
                    "unix": "1633850145"
                },
                "fee": "0.00000000",
                "current_fiat_id": "1",
                "current_fiat_amount": "5718.43",
                "tx_id": "0xtxhash",
                "is_metal_storage_fee": false,
                "tags": [],
                "public_status": "finished",
                "is_bfc": false,
                "is_card": false
            },
            "id": "XXX"
        },
        {
            "type": "wallet_transaction",
            "attributes": {
                "amount": "1.55165264",
                "recipient": "REDACTED",
                "time": {
                    "date_iso8601": "2020-08-10T17:10:46+02:00",
                    "unix": "1597072246"
                },
                "confirmations": 8,
                "in_or_out": "outgoing",
                "type": "withdrawal",
                "status": "finished",
                "amount_eur": "524.09",
                "amount_eur_incl_fee": "526.66",
                "purpose_text": "",
                "wallet_id": "XXX",
                "contact_id": "XXX",
                "confirmation_by": "email",
                "confirmed": true,
                "cryptocoin_id": "5",
                "cryptocoin_symbol": "ETH",
                "last_changed": {
                    "date_iso8601": "2020-08-10T17:12:24+02:00",
                    "unix": "1597072344"
                },
                "fee": "0.00762000",
                "current_fiat_id": "1",
                "current_fiat_amount": "524.09",
                "tx_id": "REDACTED",
                "is_metal_storage_fee": false,
                "tags": [],
                "public_status": "finished",
                "is_bfc": false,
                "is_card": false
            },
            "id": "XXX"
        }
    ],
    "meta": {
        "total_count": 191,
        "page": 1,
        "page_size": 10
    },
    "links": {
        "next": "?page=2&page_size=10",
        "last": "?page=20&page_size=10",
        "self": "?page=1&page_size=10"
    }
}
```

**Comment by LefterisJP** [comment] 2021-12-18 12:11
Hey @yabirgb shouldn't we close this? Did you confirm with the user it works or was it just me who got contacted by the user? I don't remember :rofl:

**Comment by yabirgb** [comment] 2021-12-18 12:25
I don't know who is the user that reported this, I haven't get in contact with him. About the issue is not closed because we merged against bugfixes

**Closed** 2021-12-25 00:50 UTC
Labels: exchange
