### ISSUE TITLE
miniupnpc breaks app on some osx

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#3903] opened 2022-01-03 08:58 UTC
## Problem Definition

Under osx the app fails to start

## Logs
```
2022-01-01T20:54:27.568Z: (warn): sysctl shell command to check for macOS Rosetta environment failed: Error: Command failed: sysctl sysctl.proc_translated
sysctl: unknown oid 'sysctl.proc_translated'
```

```
ImportError: dlopen(/Applications/rotki.app/Contents/Resources/rotkehlchen_py_dist/rotkehlchen/miniupnpc.cpython-37m-darwin.so, 2): Symbol not found: ___darwin_check_fd_set_overflow
  Referenced from: /Applications/rotki.app/Contents/Resources/rotkehlchen_py_dist/rotkehlchen/miniupnpc.cpython-37m-darwin.so
  Expected in: /usr/lib/libSystem.B.dylib
 in /Applications/rotki.app/Contents/Resources/rotkehlchen_py_dist/rotkehlchen/miniupnpc.cpython-37m-darwin.so
```
### System Description

Operating system: MacOS 10.14.6
Rotki version: 1.23.0

**Comment by kelsos** [comment] 2022-01-03 13:45
I am looking into it, let's see if changing the github actions runner and XCode version helps in that regard.

**Comment by fvanderelst** [comment] 2022-01-04 22:19
Thank you for addressing this.

I've re-installed from the os x binary at https://github.com/rotki/rotki/releases/download/v1.23.0/rotki-darwin_x64-v1.23.0.dmg and get the same error.

I presume the binaries get rebuilt after a merge; could you please indicate when that usually happens ?

Many thanks for your work.  I purchased the supported version !

**Comment by LefterisJP** [comment] 2022-01-05 08:44
no the binaries do not get rebuilt after a merge. You will need to wait for the next patch release which should contain this fix. We don't have an ETA but it's usually released once most bugs seen by users are addressed.

**Comment by simplysoft** [comment] 2022-01-05 12:59
We are also experiencing the same issue with the latest version 1.23.0 and mac os x 10.14.6

```
[5035] Failed to execute script rotkehlchen-script
Traceback (most recent call last):
  File "build/rotkehlchen/rotkehlchen-script.py", line 1, in <module>
  File "/Users/runner/venv/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "rotkehlchen/__main__.py", line 9, in <module>
  File "/Users/runner/venv/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "rotkehlchen/server.py", line 7, in <module>
  File "/Users/runner/venv/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "rotkehlchen/api/server.py", line 17, in <module>
  File "/Users/runner/venv/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "rotkehlchen/api/rest.py", line 105, in <module>
  File "/Users/runner/venv/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "rotkehlchen/rotkehlchen.py", line 77, in <module>
  File "/Users/runner/venv/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "rotkehlchen/usage_analytics.py", line 11, in <module>
ImportError: dlopen(/Applications/rotki.app/Contents/Resources/rotkehlchen_py_dist/rotkehlchen/miniupnpc.cpython-37m-darwin.so, 2): Symbol not found: ___darwin_check_fd_set_overflow
  Referenced from: /Applications/rotki.app/Contents/Resources/rotkehlchen_py_dist/rotkehlchen/miniupnpc.cpython-37m-darwin.so
  Expected in: /usr/lib/libSystem.B.dylib
 in /Applications/rotki.app/Contents/Resources/rotkehlchen_py_dist/rotkehlchen/miniupnpc.cpython-37m-darwin.so
```

**Comment by yabirgb** [comment] 2022-01-05 13:03
Hello @simplysoft ! Seems to be the same version reported. Should get fixed in 1.23.1. Sorry for the inconvenience

**Comment by LefterisJP** [comment] 2022-01-05 14:09
Also guys keep in mind that Mojave is no longer supported by Apple. Either upgrade soon, or find a new Mac that can upgrade to something newer otherwise a lot more things will start breaking. Eventually we will be forced to completely drop support for Mojave due to Apple's own developer toolchains.

https://en.wikipedia.org/wiki/MacOS_version_history#Releases
https://en.wikipedia.org/wiki/MacOS#Hardware_compatibility

**Comment by LefterisJP** [comment] 2022-01-06 09:49
Hey @simplysoft and @fvanderelst try this nightly version of rotki on MacOS and tell us if it works for you: https://we.tl/t-EzR4lgBxLg

**Comment by simplysoft** [comment] 2022-01-06 11:59
> Hey @simplysoft and @fvanderelst try this nightly version of rotki on MacOS and tell us if it works for you: https://we.tl/t-EzR4lgBxLg

Can confirm that it is now working with that nightly build on our machine 👍

**Comment by LefterisJP** [comment] 2022-01-06 13:48
> > Hey @simplysoft and @fvanderelst try this nightly version of rotki on MacOS and tell us if it works for you: https://we.tl/t-EzR4lgBxLg
> 
> Can confirm that it is now working with that nightly build on our machine +1

Great to hear guys. You can use that nightly build until the new patch release is out. Should be identical to the 1.23.0 except for this and some other small bugfixes we have already merged.

**Closed by LefterisJP** 2022-01-06 13:48 UTC
Labels: bug, breaking

**Comment by fvanderelst** [comment] 2022-01-06 17:28
Hey Lefteris

Thank you for this, I can confirm it works.  I am truly grateful !

Best regards

Freddie
