### ISSUE TITLE
"Exchange trades" menu option doesn't do anything

### ISSUE THREAD

**Issue by rakanalh** [rotki/rotki#284] opened 2019-02-14 20:09 UTC
## Problem Definition

On the menu, Clicking "Exchange trades" menu option does not change the current page to show whatever that page shows.

### System Description

Here add a detailed description of your system, e.g. output of the following script:

Linux archlinux 4.20.5-arch1-1-ARCH #1 SMP PREEMPT Sat Jan 26 12:59:18 UTC 2019 x86_64 GNU/Linux
/usr/bin/geth
Geth
Version: 1.8.22-stable
Git Commit: 7fa3509e2eaf1a4ebc12344590e5699406690f15
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.11.5
Operating System: linux
GOPATH=/home/rakan/Code/Go
GOROOT=/usr/lib/go
/usr/bin/parity
Parity Ethereum
  version Parity-Ethereum/v2.2.8-stable-ec81d67009-20190130/x86_64-linux-gnu/rustc1.32.0
Copyright 2015-2018 Parity Technologies (UK) Ltd.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

By Wood/Paronyan/Kotewicz/Drwięga/Volf
   Habermeier/Czaban/Greeff/Gotchac/Redmann

db9890f95f70c7109faa5d2f099c78adebd978bb

**Comment by LefterisJP** [comment] 2019-02-14 21:52
Yeah that is actually a long standing todo. It's "working as intended" at the moment since it's actually not implemented. I thought there was an issue to implement it but it seems not. We can use this issue for it.

**Comment by LefterisJP** [comment] 2020-04-05 21:44
Closing in favor of: https://github.com/rotki/rotki/issues/846

**Closed by LefterisJP** 2020-04-05 21:44 UTC
