### ISSUE TITLE
Import Binance --> Earn --> Locked staking --> Locked tokens. Currently not imported

### ISSUE THREAD

**Issue by EmilHovgaard** [rotki/rotki#3356] opened 2021-08-21 05:46 UTC

**Comment by LefterisJP** [comment] 2021-08-21 06:37
Hello @EmilHovgaard thank you for taking the time to write an issue.

This is a duplicate of https://github.com/rotki/rotki/issues/2788.

Binance has not yet added an API endpoint for this. Please talk to them to press them to do so.

**Closed by LefterisJP** 2021-08-21 06:37 UTC
