### ISSUE TITLE
Base URL Setting for hosting in subfolders and/or behind reverse proxy

### ISSUE THREAD

**Issue by thrdroom** [rotki/rotki#2934] opened 2021-05-19 08:42 UTC
## Abstract

All URLs in Rotkis frontend are hardcoded(absolute paths)(maybe in the backend too idk). Therefore running Rotki in docker can't easily be hosted in a subfolder like https://aaa.bbb.ccc/rotki/, or served from a subfolder via a reverse proxy.

Rotkis paths should be converted to relative ones.

There should be a "baseurl" parameter for the docker container and/or Rotki itself.

## Motivation

Not every user wants to have the service beeing delivered in the domain root, as there could be other services which are served in the domain root.

## Specification
Running Rotki in a Docker container.
Serving pages and services in subfolder structures via nginx reverse proxy.

**Comment by kelsos** [comment] 2021-05-19 10:00
Hey @thrdroom the frontend URLs are not really hardcoded that is Vue's default configuration when building the frontend: https://cli.vuejs.org/config/#publicpath

I will have to check if it creates any problems (or if I have to have a different configuration for the electron app compared to docker)

**Comment by thrdroom** [comment] 2021-05-23 11:24
Hey @kelsos that would be awesome if you look into that. Let me know if i can do or test anything to help you here.
Since I am bound to the provided docker image, i cant build rotki locally to host the service.

**Comment by pierrediancourt** [comment] 2022-07-17 17:32
Hello,

Thanks for fullfilling this feature request !
Some doc/guidance would make this perfect :)

From what i understand about these changes, to use of this feature we need to rebuild the image with the "VUE_APP_PUBLIC_PATH" environment variable setup to whatever we want the custom url to be (ex : /rotki/) ?
Can't that this info be passed directly during container startup ?

**Comment by kelsos** [comment] 2022-07-18 07:55
Hey @pierrediancourt I have to recheck since it has been a long time, but there is a chance that it might work without rebuilding. I remember that I had to change the vue routing for docker from history mode to hash mode otherwise things would not work.

**Comment by pierrediancourt** [comment] 2022-08-17 12:55
Hey @kelsos,

FYI
I followed the instructions here "https://github.com/rotki/rotki/pull/4040#issuecomment-1029116627" with "rotki/rotki:**v1.25.1**" instead of "rotki:test" as the image on windows 10 but couldn't get the frontend to load  
![image](https://user-images.githubusercontent.com/7483201/185135902-fddf9d17-b3fe-4308-b510-73369200bce8.png)
![image](https://user-images.githubusercontent.com/7483201/185136847-d83ffee6-0676-436a-b070-c9edd0c22adf.png)  
![image](https://user-images.githubusercontent.com/7483201/185137261-4db14021-aeee-4595-bea7-224bd77be2af.png)

**Comment by pierrediancourt** [comment] 2022-08-17 13:11
Alright,

So, the example https://github.com/rotki/rotki/pull/4040#issuecomment-1029116627 works just fine with **v1.24.0** or **v1.24.1** specified, but stops working in v1.25.0 and up when "VITE" replaces "VUEJS" i suppose (can't find the file frontend/app/public/index.html anymore for ex and it was part of this feature merge)

**Comment by kelsos** [comment] 2022-08-17 13:25
Ok there is a chance we broke it when we replaced the vue-cli we will check :) thanks

**Comment by thrdroom** [comment] 2022-11-06 12:43
Do you got any news on this? :)

**Comment by kelsos** [comment] 2022-11-06 20:35
@lukicenturi I kind of forgot about this, can you have a look at and fix it if it is possible?

**Comment by pierrediancourt** [comment] 2023-01-28 11:06
Hey,
What's the current status for this issue?

**Comment by kelsos** [comment] 2023-01-28 11:49
The fix should be available starting 1.26.2, and it should also be included in 1.26.3.

PRs that merge to bugfixes don't close automatically, that is why the issue is still open.

Can you check again if it works for you @pierrediancourt
I did test it when we merged the PR and everything seemed ok.

**Closed by kelsos** 2023-01-28 11:49 UTC

**Comment by pierrediancourt** [comment] 2023-01-28 16:36
All good, thanks a lot !
