### ISSUE TITLE
Manual liabilities are incorrectly counted in the net worth balance and in the history graph.

### ISSUE THREAD

**Issue by evilny0** [rotki/rotki#3726] opened 2021-11-17 10:52 UTC
## Problem Definition

Manual liabilities are incorrect in the dashboard net worth balance, and in the net worth history graph. There are two issues:

Liabilities which are not displayed in the dashboard (see #3724) are ignored completely. In the screenshot below, the net worth should be 570k: 595k of BTC minus the two USDC liabilities, 25k. However, it displays 585k. It's subtracting the liability amount from the dashboard, not the total amount.

Liabilities which are displayed in the dashboard are added to the net worth history graph instead of being subtracted. In the screenshot below, I took one snapshot. See how the snapshot balance is showing 605k, which is 595k + 10k ? That's the assets amount + the liability amount displayed in the dashboard.

![image](https://user-images.githubusercontent.com/8269734/142186600-0f4f923d-6484-47a8-b2cf-2b89930d673e.png)

**Comment by LefterisJP** [comment] 2021-11-17 11:37
Hey @evilny0 I can confirm this. Found the reason and will fix. The snapshot does not take into accoun all liabilities of the same type of asset.

**Comment by LefterisJP** [comment] 2021-11-17 19:26
Should be fixed by https://github.com/rotki/rotki/pull/3727.

Will go in 1.22.1

**Closed by LefterisJP** 2021-11-17 19:26 UTC
Labels: bug
