### ISSUE TITLE
Kucoin not showing in Locations dropdowns after adding

### ISSUE THREAD

**Issue by aspiers** [rotki/rotki#2470] opened 2021-02-28 17:44 UTC
## Problem Definition

As [mentioned on Discord](https://discord.com/channels/657906918408585217/745172610240872508/814683054227324959), I added my Kucoin API credentials and it correctly retrieved my balances, but it's not showing as a valid location under Trades > Filter location or Deposits & Withdrawals > Filter location.

I can check whether restarting Rotki makes Kucoin appear, but I haven't done that yet as I thought it might eliminate a possible debugging route.

## Logs

It was a few days ago but I can try to dig these out if needed.

### System Description

Operating system: openSUSE Tumbleweed
Rotki version: a recent checkout of the `develop` branch

**Comment by LefterisJP** [comment] 2021-02-28 19:26
@kelsos I feel like we have already talked about this. Did we fix this?

**Comment by kelsos** [comment] 2021-03-01 09:28
Yes, I need to have to test it, because by looking at the code the only way for this to happen would be if the trades are not loaded.

In v1.14 this would also include refreshing since on refresh the trades would be removed when refreshing and fetched again.
This will be fixed in v1.15 with the changes we did for the cache fetching.

**Comment by LefterisJP** [comment] 2021-03-10 15:04
> This will be fixed in v1.15 with the changes we did for the cache fetching.

Hey @aspiers can you check v1.15.0 to see if this still happen. If not can you close the issue?

**Comment by aspiers** [comment] 2021-03-10 16:01
Not sure how to check this because I've already added Kucoin and upgrading requires a restart, which makes the problem vanish anyway.

**Comment by LefterisJP** [comment] 2021-03-18 09:55
I added a new exchange in a clean account and can't reproduce. So I assume fixed in v1.15.0

**Closed by LefterisJP** 2021-03-18 09:55 UTC
Labels: bug, exchange
