### ISSUE TITLE
Incorrect valuation of RPL Token

### ISSUE THREAD

**Issue by fabianschu** [rotki/rotki#2137] opened 2021-01-19 10:46 UTC
## Problem Definition
- The value of Rocket Pool Token (RPL) is calculated incorrectly in the section `Blockchain Balances`
- Expected value: somewhere around 950€
- Actual value: 2550€
<img width="1367" alt="expected_valuation" src="https://user-images.githubusercontent.com/48454910/105024000-e2db4500-5a4b-11eb-913d-53b3bbd84caf.png">
<img width="1194" alt="actual_valuation" src="https://user-images.githubusercontent.com/48454910/105024056-f090ca80-5a4b-11eb-82b4-3064458fd1e8.png">

## Logs

My rotkehlchen.log seems is empty 🤔 

### System Description

Operating system: macOS 10.15.7
Rotki version: 1.11.0

**Comment by LefterisJP** [comment] 2021-01-19 11:01
> My rotkehlchen.log seems is empty

Hey Fabian thanks for the issue! The logs are probably not needed at this point, but by default they are empty. You need to activate them by enabling debug mode as per the docs here: https://rotki.readthedocs.io/en/latest/contribute.html?#id2
But I won't need them here.

So this looks like an error in the cryptocompare current price of said token: https://www.cryptocompare.com/coins/rpl/overview.
I contacted them to try and get this fixed.

In the future we will implement this issue: https://github.com/rotki/rotki/issues/2131 in order to allow you to customize the order of querying so that you can switch to coingecko as number 1 preference to be able to get around issues like that.

**Comment by LefterisJP** [comment] 2021-01-19 11:01
> My rotkehlchen.log seems is empty

Hey Fabian thanks for the issue! The logs are probably not needed at this point, but by default they are empty. You need to activate them by enabling debug mode as per the docs here: https://rotki.readthedocs.io/en/latest/contribute.html?#id2
But I won't need them here.

So this looks like an error in the cryptocompare current price of said token: https://www.cryptocompare.com/coins/rpl/overview.
I contacted them to try and get this fixed.

In the future we will implement this issue: https://github.com/rotki/rotki/issues/2131 in order to allow you to customize the order of querying so that you can switch to coingecko as number 1 preference to be able to get around issues like that.

**Comment by fabianschu** [comment] 2021-01-19 11:45
Thanks for your quick response, for contacting cryptocompare and for your outlook on #2131 :)

**Comment by vcealicu** [comment] 2021-01-19 13:36
I've passed it on to our support department. It should be fixed and getting the price from uni swap in the next few hours.

**Comment by vcealicu** [comment] 2021-01-21 17:17
Should be fixed now, it falls back to uniswap for the caclulation.

**Comment by LefterisJP** [comment] 2021-01-21 17:49
I can confirm it. https://min-api.cryptocompare.com/data/price?fsym=RPL&tsyms=USD returns the correct result and so does rotki by default now.

Thank you so much for handling this @vcealicu and team!

@fabianschu rotki should now return the correct price, since cryptocompare does so too. I am closing the issue. If there is any more problems don't hesitate to open a new one or chat with us in our discord: https://discord.gg/aGCxHG7

**Closed by LefterisJP** 2021-01-21 17:49 UTC

**Comment by fabianschu** [comment] 2021-01-24 09:26
Thanks a lot! 🎉
