### ISSUE TITLE
Blockchain per account balances total is not bold during the first load

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#952] opened 2020-04-28 20:54 UTC
## Problem Definition

It seems that during the first loading of the blockchain accounts for some weird reason the CSS for the Total row doesn' t load properly. If you navigate back and forth of the Accounts page the CSS will load properly and the Total will be properly bold.

**Comment by LefterisJP** [comment] 2020-08-01 07:59
@kelsos @isidorosp Is this still a problem? I actually can't see it when navigating to the blockchain balances for the first time. The total is properly bold.

If it's not a problem we can close this.

**Comment by isidorosp** [comment] 2020-08-01 08:20
I can't reproduce on current develop either.

**Comment by LefterisJP** [comment] 2020-08-01 09:25
All right so we close. Great to see issues closing :smile:

**Closed by LefterisJP** 2020-08-01 09:25 UTC
Labels: UI/UX, frontend, good first issue

**Comment by kelsos** [comment] 2020-08-03 07:51
> All right so we close. Great to see issues closing smile

It is always fun when you accidentally fix issues :P
