### ISSUE TITLE
ERROR rotkehlchen.api.rest Greenlet with id 4536394848: Greenlet for task 19 dies with exception: 'str' object has no attribute 'hex'.

### ISSUE THREAD

**Issue by novazembla** [rotki/rotki#4811] opened 2022-09-07 09:30 UTC
## Problem Definition
Hello, 

Unfortunately, since a few versions back the generation of a Profit & Loss statement for any year fails for me with the following error. 

```
Profit and Loss Report Generation

An unexpected response was received while generating the profit and loss report. This might indicate an issue with the generation mechanism. Please check the logs for any error messages (you might have to enable debug logging first) and create an issue.

The backend query task died unexpectedly: 'str' object has no attribute 'hex'
```

I've reported a while back that the de-serialization of the Bitstamp Songbird SGB token failed in my transactions. You've kindly fixed that but could it be that token that now breaks the Profit & Loss generation? 

If not, is there any way I can assist the debugging? 

Thanks!

## Logs

[07/09/2022 11:15:09 CEST] ERROR rotkehlchen.api.rest Greenlet with id 4536394848: Greenlet for task 19 dies with exception: 'str' object has no attribute 'hex'.
Exception Name: <class 'AttributeError'>
Exception Info: 'str' object has no attribute 'hex'
Traceback:
   File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "rotkehlchen/api/rest.py", line 284, in _do_query_async
  File "rotkehlchen/api/rest.py", line 1584, in _process_history
  File "rotkehlchen/rotkehlchen.py", line 653, in process_history
  File "rotkehlchen/accounting/accountant.py", line 151, in process_history
  File "rotkehlchen/accounting/accountant.py", line 279, in _process_event
  File "rotkehlchen/accounting/structures/base.py", line 274, in should_ignore
  File "rotkehlchen/accounting/structures/base.py", line 175, in serialized_event_identifier

### System Description
Operating system: MacOS
Rotki version: 1.25.3

**Comment by LefterisJP** [comment] 2022-09-07 09:49
Hello @novazembla thank you for the issue.

Hey @prettyirrelevant can you chime in here?

Look at where the error is. In bugfixes (1.25.3) branch we are missing something there which is now added in develop:

1.25.3: https://github.com/rotki/rotki/blob/v1.25.3/rotkehlchen/accounting/structures/base.py#L172
develop: https://github.com/rotki/rotki/blob/edbdb8cdc866ad4a62642e475a90a3e9539e6b31/rotkehlchen/accounting/structures/base.py#L172

```python
or self.event_identifier.startswith('rotki_events'.encode())
```

Is that enough? Can you explain what may be happening here?

**Comment by prettyirrelevant** [comment] 2022-09-07 09:58
I think that's not the issue.
> exception: 'str' object has no attribute 'hex'.

It's more of a bug where `event_identifier` appears as a `str` not `bytes`.

**Comment by LefterisJP** [comment] 2022-09-07 11:57
> I think that's not the issue.
> 
> > exception: 'str' object has no attribute 'hex'.
> 
> It's more of a bug where `event_identifier` appears as a `str` not `bytes`.
> 
> Hey @novazembla! I'll look into it asap

Sure but why and under which circumstances. And remember this is 1.25.3, so not develop for the user.

**Comment by prettyirrelevant** [comment] 2022-09-08 16:18
Hey @novazembla. Apologies for my late response.
To resolve this, could you please provide logs to trace the bug better?

To protect your information, do join our Discord server using this link https://discord.gg/aGCxHG7 and shoot me a DM @ **prettyirrelevant#2597**

Thanks.

**Comment by LefterisJP** [comment] 2022-09-20 21:35
Has there been any progress here @prettyirrelevant ?

**Comment by LefterisJP** [comment] 2022-10-24 07:14
Hey @prettyirrelevant if there is no progress on this due to lack of input from user and/or inability to reproduce either close explaining this or get the relevant info and post a progress update here.

**Comment by prettyirrelevant** [comment] 2022-10-24 10:15
I was unable to reproduce the bug in any way.  Nonetheless, I'm awaiting a final response from the user. If I receive no response by tomorrow morning, you can close the issue.

**Comment by LefterisJP** [comment] 2022-10-28 21:36
I see no update here so I am closing the issue

**Closed by LefterisJP** 2022-10-28 21:36 UTC
