### ISSUE TITLE
Edit ledger action date time

### ISSUE THREAD

**Issue by a7e8** [rotki/rotki#2151] opened 2021-01-21 04:05 UTC
## Problem Definition

When editing a ledger action the date picker does not populate in the same way it does when editing a trade.

## Logs

n/a

### System Description

Operating system: Mac OS X
Rotki version: 1.12.2

**Comment by LefterisJP** [comment] 2021-01-21 08:33
Hey @a7e8 can you better specify exactly what you think is the problem here? What did you expect it to be and what does it end up being?

**Comment by a7e8** [comment] 2021-01-24 08:27
Expected: The date picker should show the date and time of the text field
Actual: The date picker shows the current date and time

**Comment by LefterisJP** [comment] 2021-01-24 09:02
Hmm @a7e8 I can't reproduce this.

When i try it either with v1.12.2 or with the current development branch it's populated fine.

What is indeed different and not respected though is the datetime format that the user has customized. It seems to be using the default. Is this by any change the discrepancy you are seeing?

**Comment by a7e8** [comment] 2021-01-29 08:54
No I didn't customize the datetime format. I just tried it again and when I add a new ledger action the year is 1970...

**Comment by kelsos** [comment] 2021-01-29 09:08
The 1970 thing will be fixed in the next release, but we still haven't managed to reproduce the edit problem, unfortunately. There are some changes in the component that will go in the next release. Please let us know if the issue happens in the next release or if it is fixed.

**Comment by a7e8** [comment] 2021-02-18 09:21
Still happens in 1.14.1

**Comment by kelsos** [comment] 2021-02-18 09:41
@a7e8 I cannot replicate any of these issues I will try again on a mac, but on Linux, I cannot see anything.

Would it be possible for you to create a new account (to avoid leaking any private information),
and make a small video showing the exact problem?

**Comment by LefterisJP** [comment] 2021-02-24 20:46
should be fixed by #2418 and be part of v1.14.2

**Closed by LefterisJP** 2021-02-24 20:46 UTC
