### ISSUE TITLE
Misattribution of BitPanda CryptoIndex fees

### ISSUE THREAD

**Issue by schamama** [rotki/rotki#5850] opened 2023-04-02 16:43 UTC
When generating my Profit'n'Loss report 2022 for BitPanda involving buying one of BitPanda's Cryptoindex products ("BC5", "BC10", or "BC25".), rotki quickly ran into the problem of "Incomplete cost basis information for spend". Upon investigation, it seems as if rotki wrongly interprets/attributes fees on BitPanda (fees are paid in BEST) when it comes to one of their CryptoIndex products.

In my instance, I just had opened a BitPanda account for the first time, bougtht 200 BEST for the first time ever, and immediately bought a CryptoIndex "BC10" with EUR. Buying that CryptoIndex triggered fees of 31,75 BEST in total(!)  for actually buying a total of 10 different cryptocurrencies. However, looking at my "Profit'n'Loss" report, rotki wrongly listed each(!) of the 10 trades individually (!) with a fee of 31.75! As a consequence, rotki, correctly assuming I only had 200 BEST available, but wrongly assuming that I just triggered fees of 317,5 BEST (=10 trades á 31,75 BEST), runs into the problem of "Incomplete cost basis information for spend".

Please look into BitPanda fee attribution when it comes to their CryptoIndices! (I am happy to provide you an API key if needed, as well as the rotki P'n'L table for references.)

**Comment by LefterisJP** [comment] 2023-04-02 16:55
hey @schamama welcome!

Thank you so much for reporting the issue and with a lot of details too! As nobody from the team uses Bitpanda and the integration was made by an external it would be really good to get an API key to fix this.

Can you pop by our discord: https://discord.gg/aGCxHG7 (need DMs open to solve a captcha challenge).
There (most surely weekdays from 9:00-18:00 German time) you can find someone from the dev team to share a **read only** API key with so we can reproduce.

**Comment by yabirgb** [comment] 2023-04-19 17:58
Update: The issue happens to an error in the data returned by bitpanda. The user has already contacted support with the info that we have provided

**Comment by LefterisJP** [comment] 2023-05-16 08:50
So if the issue is confirmed to be on the side of bitpanda and it has been reported nothing remains to be done here so I am closing the issue.

**Closed by LefterisJP** 2023-05-16 08:50 UTC
Labels: bug
