### ISSUE TITLE
Maker DAO ETH deposits are double-counted

### ISSUE THREAD

**Issue by alifier** [rotki/rotki#2294] opened 2021-02-05 00:50 UTC
## Problem Definition
My MakerDAO ETH-A vault balance seems to be counted as ETH and as WETH resulting in a double count.

### System Description

Operating system: MacOS Big Sur
Rotki version: 1.13.1

**Comment by LefterisJP** [comment] 2021-02-05 08:17
I can confirm this. This must have started happening today as it did not happen yesterday. Let me investigate. I suspect the defi adapter SDK we use started returning different results, resulting in double counting.

**Comment by LefterisJP** [comment] 2021-02-05 08:41
So @alifier this should be fixed by https://github.com/rotki/rotki/pull/2296. And the problem seems to be only in v1.13.1. We will include the fix in either a next patch release (v1.13.2) or our next big release v1.14.0. Doing a patch release or not depends on the amount of bugs fixed.

**Closed** 2021-02-05 09:33 UTC
Labels: bug

**Comment by LefterisJP** [comment] 2021-02-07 16:26
The fix for this is now included in a release. Download patch release v1.13.2: https://github.com/rotki/rotki/releases/tag/v1.13.2
