### ISSUE TITLE
Polkadot and Kusama integration

### ISSUE THREAD

**Issue by mruepp** [rotki/rotki#3161] opened 2021-07-07 06:01 UTC
## Abstract

There is a lack in the polkadot ecosystem of an asset accounting and tracking software. Rotki is a very good application but mainly lacks polkadot/Kusama integration

## Motivation

Polkadot/Kusama will become a huge ecosystem. Possibly larger than Ethereum. The concept of parachains however makes this a quite complicated and time consuming task to integrate Rotki with it.

## Specification

- Track staking on chain/exchanges (kraken, ...)
- Enable staking to count against income balance opposite to not staked assets which count against wealth/property tax
(This is basically a jurisdiction issue, so some countries count staking against income, some count every asset transfer as taxable, some count it only as property if kept one year, etc) so this is a whole new feature to change tax jurisdiction.
- Enable to track bonded crowdloaned assets
- Enable parachain asset tracking (onchain/exchanges)
- Maybe support even for crowdloans out of rotki. Maybe Rotki even as a Polkadot Wallet

##Funding
So there is the Kusama & Polkadot Treasury. It is exactly for such projects to support.
I suggest creating a proposal on either Kusama or Polkadot (or one for each integration)
I am not sure if It would be feasable for me to create such a proposal because I am not involved with the project so I suggest you guys take the effort, I am willing to support:
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama.elara.patract.io#/treasury
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.polkadot.io#/treasury
You can find info how to create a proposal here:
https://wiki.polkadot.network/docs/learn-treasury/

##Tech
There are various api´s for interfacing with polkadot:
https://polkadot.network/polkascan-development-update-5/
https://pypi.org/project/py-substrate-api/
https://github.com/polkascan/py-substrate-interface
https://github.com/polkascan/py-scale-codec

Would love to see a good integration. Thanks for your good work!

**Comment by LefterisJP** [comment] 2021-07-07 07:29
Hey @mruepp thank you for your issue. It is a bit too generic and all encompassing. It would be best if a separate issue was made for each point that does not have an issue.

Related issues:
- Original polkadot/kusama support issue: https://github.com/rotki/rotki/issues/1081
- Read and show kusama transactions: https://github.com/rotki/rotki/issues/2385
- Support for polkadot: https://github.com/rotki/rotki/issues/3125

From your points:

> Track staking on chain/exchanges (kraken, ...)

The on-exchange staking is per exchange and we already have issues for each supported exchange. e.g. kraken: https://github.com/rotki/rotki/issues/569

> Enable staking to count against income balance opposite to not staked assets which count against wealth/property tax
(This is basically a jurisdiction issue, so some countries count staking against income, some count every asset transfer as taxable, some count it only as property if kept one year, etc) so this is a whole new feature to change tax jurisdiction

Hmm I do not understand this. You would have to make an issue specific to this since this is as you say an accounting jurisdiction option and would need ample specification.

> Enable to track bonded crowdloaned assets

I don't know what that is. Would proably need its own issue.

> Enable parachain asset tracking (onchain/exchanges)

Same here. I have heard of parachains but have not had any time to actually look into them.

-----

Now for funding. It's not a matter of funding. We already have had some intiial funding from kusama treasury for the kusama integration which exists now in rotki. The problem is a technical one.

There exists no good way (at least up to the point in time we spent time on integration) to query kusama (and by extension I guess polkadot) transactions for an address, and staking info etc.

The node has no way to query all transactions for it and you need to find some centralized api to get that info from. And the subscan api is closed with an api key.

I know the graph will expand on kusama too so hopefully subgraphs in the decentralized way of the graph will be created.

Ideally we will find more people to help us with the code, and have people from the community open PRs as we ourselves are also overwhelmed. Not nearly enough time for everything.

---

Once all sub-isses are created I would like to close this one as it's best to have specific smaller and actionable items.

**Comment by mruepp** [comment] 2021-07-07 08:08
You're right a bit generic. Will try to split it up and provide more infos

**Comment by bloxster** [comment] 2021-08-21 09:52
Maybe this could be of some help to see balance of all various Substrate wallet addresses from anywhere:

[Introducing Sub ID: The One Stop Shop For All Your Substrate Addresses And Balances](https://app.subsocial.network/@subsocial/introducing-sub-id-the-one-stop-shop-for-all-your-substrate-19172)

**Comment by LefterisJP** [comment] 2021-12-24 13:00
Closing this one as we already have this implemented in rotki. There is still lots of improvements and things to do but we would probably act on specific issues instead of one big one like this.

**Closed by LefterisJP** 2021-12-24 13:00 UTC
