### ISSUE TITLE
Any way to run JUST the "backend server"?

### ISSUE THREAD

**Issue by pereztechseattle** [rotki/rotki#1715] opened 2020-11-10 14:29 UTC
I really like some of Rotki's features (particularly the REST API and the /ETH/defi endpoint). I've been trying to use Rotki as a backend for my trading bots, but I'm to the point now where I'm going to have to find an alternative unless I can figure out some other way to run this thing.  It's simply too flaky to use as a backend due to it dying periodically. 

Is there some way to run *just* the REST API?  I'm hoping that would cut down on some of the runtime failures.  Also, logging in with username and password is an unnecessary risk in my mind.  I'd much prefer to get rid of that part.

Any ideas appreciated.  I haven't been able to find any product that does just the backend REST API piece.  That's really the only piece I'm after.... a more stable version.  :) thanks!

**Comment by pereztechseattle** [comment] 2020-11-10 14:32
Out of curiosity...  what was the "backend API" piece built for anyway?

**Comment by LefterisJP** [comment] 2020-11-10 15:23
>  I've been trying to use Rotki as a backend for my trading bots, but I'm to the point now where I'm going to have to find an alternative unless I can figure out some other way to run this thing. It's simply too flaky to use as a backend due to it dying periodically.

The periodically dying issue you refer to is I assume: https://github.com/rotki/rotki/issues/1514?

We have not yet managed to reproduce it and nobody else has reported it so we don't have too much to go on in terms of identifying and fixing it. If you are a developer any help here is really appreciated. It also seems to be OSX specific.

> Is there some way to run just the REST API? I'm hoping that would cut down on some of the runtime failures.

Yes you can run just the rest api if you run it from source. Please read the code and the docs for more info.

You can just run the backend `python -m rotkehlchen` and the rest api is open by default. Judging from the error in the issue, running the backend alone will not result in the same problem.

>  Also, logging in with username and password is an unnecessary risk in my mind. I'd much prefer to get rid of that part.

The username is just a way to identify the database. A corresponding directory with that username is created in the rotki data folder. The password is to encrypt the database.


-----

I hope you got all the information you needed. Since this is just a question and it's not really an actionable issue I am going to close it. Also please note your use-case is quite unique and definitely not the main use-case of Rotki. Still if we can somehow help you achieve your goals it's going to make me happy.

Making an issue with a question will get you an answer, but it's always better to ask in our discord: https://discord.gg/aGCxHG7
There you can also get more real-time support and probaly help from more people.

**Closed by LefterisJP** 2020-11-10 15:23 UTC

**Comment by pereztechseattle** [comment] 2020-11-10 15:41
didn't know about the discord.  thanks!!

**Comment by LefterisJP** [comment] 2020-11-10 15:44
Another thing we can do is publish the python binaries also as artifacts in the releases. We also want to allow the user eventually run the backend in one machine and run the frontend in a different machine or even in their mobile phone (look at our docker work).
